### PR TITLE
Added basic velocity and position coordinate transformation

### PR DESCRIPTION
**Pull request by ritzvik**
Also moved utils to a folder.
Still need to handle conversions with units!

### CODE REVIEW

**Comment by ritzvik** [comment]
you can start to add codecov! @shreyasbapat

**Comment by ritzvik** [comment]
Now both input and output can be obtained in cartesian coords.
Great for plotting

**Comment by ritzvik** [comment]
Also, currently coverage is 67%.

**Comment by shreyasbapat** [comment]
I will halt this PR for a moment and deploy several other testing tools so that we ensure that the tests run perfectly on CI :)

**Comment by ritzvik** [comment]
Trying again!!

**Pull request closed without merging**
