### PR TITLE
Add animated plots for StaticGeodesicsPlotter.

### PR DESCRIPTION
**Pull request by Varunvaruns9**
Fixes parts of #36

This PR adds method `animate` for simulation of orbits.

Demo:
ezgif com-video-to-gif

@shreyasbapat @spino17 FYI.

### CODE REVIEW

**Comment by shreyasbapat** [comment]
@Varunvaruns9 Can you please fix this first #150 ?

**Comment by shreyasbapat** [comment]
And why on the earth do this PR has just 6 checks?

**Comment by shreyasbapat** [comment]
Can you close and open this PR once?

**Comment by Varunvaruns9** [comment]
Rest of the checks still don't start :/

**Comment by Varunvaruns9** [comment]
Opening new PR to trigger tests.

**Pull request closed without merging**
