### PR TITLE
Added changes for running the CI in parallel

### LINKED ISSUE #126: Make the tests on CI parallel
🐞 **Problem**
As of now, the tests on various CI are running sequentially. It's not a problem right now, but we might want to run them in parallel as the number of tests grows.

🎯 **Goal**
  - Parallelize the tests on `TravisCI`, `CircleCI` and `appveyor`.

💡 **Possible solutions**
  - On personal computer, tests are be parallelized by `pip install pytest-xdist` and then `pytest -n 8 -vv`
  - Maybe this could be the way. See https://docs.pytest.org/en/3.0.0/xdist.html
  - After figuring out the solution, change the `.yml` files for each of the CIs

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #126`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by yashrsharma44**
Fixes #126 
* Added parallel tag for running 8 subprocesses
* Added the changes in `.circleci/config.yml`, `.travis.yml` and `appveyor.yml`
* Added the package `pytest-xdist` in the dev requirements in `setup.cfg`

### CODE REVIEW

**Comment by shreyasbapat** [comment]
I didn't see the speed! Did you notice any difference?

**Comment by shreyasbapat** [comment]
This will need a rebase :)

**Comment by ritzvik** [comment]
Maybe this would need some settings in the CI dashboard also. @shreyasbapat ? Maybe things are running on one core but multiple threads.

BTW @yashrsharma44 great work. Thanks

**Comment by shreyasbapat** [comment]
What does CI Dashboard mean? I didn't understood :sweat_smile:

**Comment by ritzvik** [comment]
> What does CI Dashboard mean? I didn't understood 😅

Settings from within the CI provider I meant . 😄

**Comment by shreyasbapat** [comment]
I fear we can't change that! We are on a free plan xD

**Comment by yashrsharma44** [comment]
So running 8 threads does not provide any speedup?

**Comment by ritzvik** [comment]
> So running 8 threads does not provide any speedup?

If the Ci is set to work on single core, I'm afraid there wouldn't be benefit of multiple threads.
I'll research about this. CircleCI has options to split tests, AFAIK.

**Comment by ritzvik** [comment]
CircleCI splitting tests : https://circleci.com/docs/2.0/parallelism-faster-jobs/#splitting-test-files

**Comment by yashrsharma44** [comment]
Hey, can this PR be merged? If anything is required, I am happy to add them up.

**Comment by ritzvik** [comment]
@yashrsharma44 Sorry for the delay!!
From what I know, CircleCI is providing us 2 CPUs, so parallelizing is viable there. So, let tests run parallel on CircleCI for now, and revert the changes in travis & appveyor as a clear picture can't be obtained regarding them.


Squash and rebase the commits, and hopefully it would be merged.

Thanks

**Comment by yashrsharma44** [comment]
Thanks for the feedback @ritzvik ! I have updated my PR.

**Comment by ritzvik** [comment]
@shreyasbapat LGTM

**Comment by shreyasbapat** [comment]
Too good!

**Pull request merged**
