### PR TITLE
Fixes #449 - Commit 0

### LINKED ISSUE #449: Introduce "name" parameter in Metric Tensor
🐞 **Problem**
Provision of `name` parameter is already there in the base class `BaseRelativityTensor` and now it's time to extend it to `MetricTensor`.

🎯 **Goal**

  - [ ] change `symbolic/metric.py`
  - [ ] Introduce `name` in predefined metrics in `symbolic/predefined`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Fixes #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by JeS24**
Fixes #449 

@ritzvik @shreyasbapat Please review the PR. Thanks.

### CODE REVIEW

**Comment by JeS24** [comment]
Also, I have certain queries and suggestions. But let's discuss them, after the PR review.

**Comment by ritzvik** [comment]
Looks good to me.
@JeS24 , you got it at first shot!

**Comment by ritzvik** [comment]
Please do discuss your queries and suggestions here, we can make another PR for the same.

**Comment by JeS24** [comment]
> Please do discuss your queries and suggestions here, we can make another PR for the same.

Okay, here goes:

#### Suggestions:
1. Currently, both `__str__` and `__repr__`,  in `einsteinpy.symbolic.tensor.py > Tensor`, don't show the Tensor name. Is adding `name` to `str` and/or  `repr` a good idea? For example, the output of `str(tensor)` could be something like:

```
Tensor TensorName 
[[...]]
```

2. A tag added to the Tensor `name`, after **binary** changes are made to the Tensor to mark the respective changes, would be nice. For example, after `config_change` or `lorentz_transformation`, tags, like `_cc` or `_lt` can be appended/removed.
3. I think, the Metric Functions in `einsteinpy.symbolic.predefined` should be refactored to have "Metric" in their function names, in order to better reflect their exact 'function'. I'm aware, this will break a lot of stuff in the codebase, particularly in examples.

#### (General) Query:
4. Are the tests entirely automated?

Apart from this, I have a few queries, that are unrelated to this issue. Would Riot be a better place to bring them up?

**Comment by ritzvik** [comment]
> > Please do discuss your queries and suggestions here, we can make another PR for the same.
> 
> 
> 
> Okay, here goes:
> 
> 
> 
> #### Suggestions:
> 
> 1. Currently, both `__str__` and `__repr__`,  in `einsteinpy.symbolic.tensor.py > Tensor`, don't show the Tensor name. Is adding `name` to `str` and/or  `repr` a good idea? For example, the output of `str(tensor)` could be something like:
> 
> 
> 
> ```
> 
> Tensor TensorName 
> 
> [[...]]
> 
> ```
> 

Yes, it’s a pretty good idea. Do open an issue for that.

> 
> 
> 2. A tag added to the Tensor `name`, after **binary** changes are made to the Tensor to mark the respective changes, would be nice. For example, after `config_change` or `lorentz_transformation`, tags, like `_cc` or `_lt` can be appended/removed.
> 

Little complicated to implement, but again open a separate issue :)

> 3. I think, the Metric Functions in `einsteinpy.symbolic.predefined` should be refactored to have "Metric" in their function names, in order to better reflect their exact 'function'. I'm aware, this will break a lot of stuff in the codebase, particularly in examples.
> 
> 

This needs some considerations. Let’s put a hold to it but I’ll keep this in mind.

> 
> #### (General) Query:
> 
> 4. Are the tests entirely automated?
> 
> 

Yes, thanks to CircleCI, GitHub and appveyor. But new tests are added manually for new functionalities. If you get a chance, go through the tests. 

> 
> Apart from this, I have a few queries, that are unrelated to this issue. Would Riot be a better place to bring them up?

**Comment by ritzvik** [comment]
Also, riot would be the place for lengthy, insightful discussions. 
Actually, depends on the purview of the discussion. Whether it is general or issue-specific.

**Comment by ritzvik** [comment]
And lastly I forgot in your case.
Cheers to your first PR 🤟🏿✌🏿

**Comment by JeS24** [comment]
> And lastly I forgot in your case.
> Cheers to your first PR 🤟🏿✌🏿

@ritzvik Thanks. I have opened two issues, pertaining to points 1 (#453) and 2 (#454). As for 3, I understand.

**Pull request merged**
