### PR TITLE
BL/Spherical coordinate transforms

### LINKED ISSUE #118: Make a utility file for BL/Spherical coordinate conversion
🐞 **Problem**
The title is self-explanatory.

💡 **Possible solutions**

  - Direct conversion formulas can be written
  - or, In order to make coder's life easy, conversions can be done using Cartesian in between. That is `Spherical->Cartesian->Boyer Lindqiuist` and vice versa.
  - Code it in the lines of `utils/coord_transforms.py` and 
`utils/bl_coord_transforms.py`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #118>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by pmk21**
Fixes #118  

@ritzvik Need some help writing tests and any more functions to be added?

### CODE REVIEW

**Comment by ritzvik** [comment]
Thanks @pmk21 for your efforts

`isort /path/to/file/name` to sort the imports. And things in `utils` are seriously messed up. We may not be able to merge it now. Once that is figured out, we'll see to this. Sorry for this. We may have to make submodules within `utils` like `coordinates`, `metric` and `symbolic`. This would be figured out through an extensive discussion on the issue #121 

Until this, we may have to keep it on hold. I'll surely help with the tests, once this thing is sorted out.

I'm really sorry for this. We should have seen it coming and made the `utils` modular from day 0.

Thanks again @pmk21

**Comment by ritzvik** [comment]
@pmk21 I've raised it on riot. Kindly, provide your suggestions on this. Comment on #121

**Comment by shreyasbapat** [comment]
@pmk21 Would you first like to work on #121 ?

**Comment by pmk21** [comment]
Yes, would love to. But, probably need some help with it @shreyasbapat

**Comment by shreyasbapat** [comment]
Always happy to help!

Best,
Shreyas

>

**Comment by ritzvik** [comment]
@pmk21 could you append the functions in `bl_coord_transforms.py`. Just separate out the file by writing a comment `# Spherical/BL conversions` 😃 . We would migrate the functions to the class we discussed anyway, when they get in a proper shape. 

For the tests:
  - When `a=0` BL coordinates are just Spherical Coordinates. So keeping a=0, test the equality of BL and Spherical coordinates. This means when `ans_vec = BLToSpherical_pos(pos_vec, 0)`, `assert_allclose(ans_vec, pos_vec)` should not throw `AssertionError`. Same goes for `SphericalToBL_pos()` and functions of `_vel()` type.
  - Secondly, cycle should be same. That means when `a1= BLToSpherical_pos(pos_vec, 0); a2 = SphericalToBL_pos(a1, 0.)`, `a2==pos_vec`. Implement with `assert_allclose()`.
  - For reference, see `tests/test_utils/test_bl_coord_transforms.py`.
  - You may need to rebase this branch

Finally, I'm sorry to keep this PR waiting. I figured out, it would be a matter of copy-paste ones the coordinates module is built.

Do not forget `black` & `isort`

Thanks @pmk21 for your contribution.

**Comment by shreyasbapat** [comment]
Plus, a rebase!

**Comment by pmk21** [comment]
Didn't quite understand what to rebase. Sorry I'm kinda new to this, would you please explain?

**Comment by ritzvik** [comment]
> Didn't quite understand what to rebase. Sorry I'm kinda new to this, would you please explain?

@pmk21 It's all right. Everybody is a newbie at some point.

As you can see the einsteinpy master has moved some commits ahead since you opened this PR. So your branch may be lagging behind and you made the changes on an old image of the repo. So, it is sensible to update your copy and replay your changes on top of it.

  - Set upstream if you have not done so. `git remote add upstream https://github.com/einsteinpy/einsteinpy`
  - Fetch the HEAD pointer. `git fetch upstream`
  - Pull the latest changes. `git pull --rebase upstream master`. `--rebase` makes sure that merge commits do not appear
  - `git log --oneline` to see the commits. If you do it right, you may see your unmerged commits on top of commits from einsteinpy master.

Feel free to ask anything, if further doubt arises.

Thanks again @pmk21

**Comment by pmk21** [comment]
Thanks a lot for the help @ritzvik. What about tests for the functions `S2BL_units` and `BL2S_units`?

**Comment by ritzvik** [comment]
> Thanks a lot for the help @ritzvik. What about tests for the functions `S2BL_units` and `BL2S_units`? And the `isort` command isn't working properly.

Can you do `from einsteinpy import utils` and then use the functions like `utils.SphericalToCartesian_pos()`

  - Also, leave out the tests. I would be give them to you. Just append them to end of file `tests/test_utils/test_bl_coord_transforms.py`

**Comment by ritzvik** [comment]
> > Thanks a lot for the help @ritzvik. What about tests for the functions `S2BL_units` and `BL2S_units`? And the `isort` command isn't working properly.
> 
> Can you do `from einsteinpy import utils` and then use the functions like `utils.SphericalToCartesian_pos()`
> 
> * Also, leave out the tests. I would be giving them to you in a while. Just append them to end of file `tests/test_utils/test_bl_coord_transforms.py`. Meanwhile, squash the commits.
> * Also, `black` and `isort`.

Let the tests remain, I would be just suggesting some changes

**Comment by pmk21** [comment]
The `from einsteinpy import utils` in the `bl_coord_transforms.py` is failing in CircleCI quality tests.

**Comment by ritzvik** [comment]
Append them to `test_bl_coord_transforms.py`. Thanks for the tests, I have just edited them a little bit and added tests for functions `_units()`

```
# test for Spherical/BL transforms


@pytest.mark.parametrize(
    "pos_vec", [np.array([12, 20 * np.pi / 180, 60 * np.pi / 180])]
)
def test_BLToSpherical_pos_a0(pos_vec):
    ans_vec = utils.BLToSpherical_pos(pos_vec, 0.0)
    assert_allclose(ans_vec, pos_vec)


@pytest.mark.parametrize(
    "pos_vec", [np.array([12, 20 * np.pi / 180, 60 * np.pi / 180])]
)
def test_SphericalToBL_pos_a0(pos_vec):
    ans_vec = utils.SphericalToBL_pos(pos_vec, 0.0)
    assert_allclose(ans_vec, pos_vec)


@pytest.mark.parametrize(
    "pos_vec, vel_vec",
    [(np.array([12, 20 * np.pi / 180, 60 * np.pi / 180]), np.array([0.0, 0.0, 10]))],
)
def test_BLToSpherical_vel_a0(pos_vec, vel_vec):
    ans_vec = utils.BLToSpherical_vel(pos_vec, vel_vec, 0.0)
    assert_allclose(vel_vec, ans_vec)


@pytest.mark.parametrize(
    "pos_vec, vel_vec",
    [(np.array([12, 20 * np.pi / 180, 60 * np.pi / 180]), np.array([0.0, 0.0, 10]))],
)
def test_SphericalToBL_vel_a0(pos_vec, vel_vec):
    ans_vec = utils.SphericalToBL_vel(pos_vec, vel_vec, 0.0)
    assert_allclose(vel_vec, ans_vec)


@pytest.mark.parametrize(
    "pos_vec, a",
    [
        (np.array([100, 2 * np.pi / 3, 1.0]), 11.11),
        (np.array([10, np.pi / 3, 2.5]), 0.5),
        (np.array([1, 1e-3, 0]), 0.1),
    ],
)
def test_BLToSpherical_cycle_pos(pos_vec, a):
    pos_vec2 = utils.SphericalToBL_pos(pos_vec, a)
    pos_vec3 = utils.BLToSpherical_pos(pos_vec2, a)
    assert_allclose(pos_vec, pos_vec3, atol=1e-6)


@pytest.mark.parametrize(
    "pos_vec, vel_vec, a",
    [
        (np.array([100, 2 * np.pi / 3, 1.0]), np.array([-2, -2, -2]), 11.11),
        (np.array([10, np.pi / 3, 2.5]), np.array([0, 0, 0]), 0.5),
        (np.array([1, 1e-3, 0]), np.array([100, 100, -100]), 0.1),
    ],
)
def test_BLToSpherical_cycle_vel(pos_vec, vel_vec, a):
    pos_vec2 = utils.SphericalToBL_pos(pos_vec, a)
    vel_vec2 = utils.SphericalToBL_vel(pos_vec, vel_vec, a)
    vel_vec3 = utils.BLToSpherical_vel(pos_vec2, vel_vec2, a)
    assert_allclose(vel_vec, vel_vec3, rtol=0.0, atol=1e-5)


@pytest.mark.parametrize(
    "pos_vec, vel_vec, ans_vel_vec",
    [
        (
            [20 * u.m, 90 * u.deg, 45 * u.deg],
            [-1 * u.m / u.s, 1 * u.deg / u.s, 0 * u.rad / u.s],
            np.array([-1, np.pi / 180, 0]),
        )
    ],
)
def test_BL_Spherical_units(pos_vec, vel_vec, ans_vel_vec):
    a = utils.BL2S_units(pos_vec, vel_vec, 0.0)
    tmp = np.array([t.value for t in a[1]])
    assert_allclose(ans_vel_vec, tmp, rtol=0.0, atol=1e-5)
    a = utils.S2BL_units(pos_vec, vel_vec, 0.0)
    tmp = np.array([t.value for t in a[1]])
    assert_allclose(ans_vel_vec, tmp, rtol=0.0, atol=1e-5)
```

`black` and `isort`, dont forget

**Comment by pmk21** [comment]
Sorry for the extreme trouble. I ran `isort` on `test_bl_coord_transforms.py` and it is failing the quality tests.

**Comment by ritzvik** [comment]
> Sorry for the extreme trouble. I ran `isort` on `test_bl_coord_transforms.py` and it is failing the quality tests.

isort and black are to run everywhere I guess. Plus, I can't figure out why `mypy` is having issues in CircleCI

**Comment by ritzvik** [comment]
Meanwhile you may remove the [WIP] from title. I think it's pretty close to being merged!

**Comment by ritzvik** [comment]
Might be the case that isort may not be functioning correctly on your system.

On the test file use :
```
import numpy as np
import pytest
from astropy import units as u
from numpy.testing import assert_allclose

from einsteinpy import utils

```

On the `bl_coord_transforms.py` use:
```
import astropy.units as u
import numpy as np

from einsteinpy import utils

```

This time, just use `black` as I have already `isort`ed them on my pc

**Comment by ritzvik** [comment]
@pmk21 sorry for the trouble. I don't know why isort is not passing.

**Comment by ritzvik** [comment]
Meanwhile squash the commits into 1 or 2.
`git reset --soft HEAD~9`
 
All the changes you have done, would be reverted and become staged and unstaged changes. Use `git status` to verify.
Then you may create a separate commits for addition to new coordinate conversions and tests.

You may also want to read abut squashing https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by ritzvik** [comment]
@pmk21 I have made a PR to your `bl_sph_transforms`. Merge that, I believe it would sort this thing

**Comment by pmk21** [comment]
> Meanwhile squash the commits into 1 or 2.
> `git reset --soft HEAD~9`
> 
> All the changes you have done, would be reverted and become staged or unstaged changes. Use `git status` to verify.
> Then you may create a separate commits for addition to new coordinate conversions and tests.
> 
> You may also want to read abut squashing https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

Thanks a lot for the help @ritzvik. Sorry for bothering you and creating a mess here.

**Comment by ritzvik** [comment]
> > Meanwhile squash the commits into 1 or 2.
> > `git reset --soft HEAD~9`
> > All the changes you have done, would be reverted and become staged or unstaged changes. Use `git status` to verify.
> > Then you may create a separate commits for addition to new coordinate conversions and tests.
> > You may also want to read abut squashing https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit
> 
> Thanks a lot for the help @ritzvik. Sorry for bothering you and creating a mess here.

No problem. Even I was not clear how to go ahead with the tests and all. Still the `mypy` problem in CircleCi is there.

**Comment by ritzvik** [comment]
Just one last change
```
import astropy.units as u
import numpy as np

from . import coord_transforms as sph

```

replace all `utils.function()` with `sph.function()` 
apply `black`

**Comment by ritzvik** [comment]
@shreyasbapat This PR is ready to be merged.

Thanks a lot @pmk21 for your continued patience and responding to all the requested changes. I believe you have put a lot of effort after it.

**Comment by shreyasbapat** [comment]
> @shreyasbapat This PR is ready to be merged.

Not yet!

**Comment by shreyasbapat** [comment]
Closed through https://github.com/einsteinpy/einsteinpy/pull/139/commits/0a2e76dd518031e97bd6ae504d05a34f783bc481 in #139

**Comment by shreyasbapat** [comment]
Thanks @pmk21  I made you the author of a commit in my PR regarding this. I used all your methods. Thanks a lot for your help ;)

**Comment by shreyasbapat** [comment]
> @pytest.mark.parametrize(
    "pos_vec", [np.array([12, 20 * np.pi / 180, 60 * np.pi / 180])]
)

You never use parametrize for passing single set of values :) 

Have a look at the documentation: https://docs.pytest.org/en/latest/parametrize.html

**Comment by shreyasbapat** [comment]
> Might be the case that isort may not be functioning correctly on your system.

Check the version of isort in your system. Circle CI installs the latest!

**Pull request closed without merging**
