### PR TITLE
Coordinate conversion fixed

### PR DESCRIPTION
**Pull request by Manvi07**
Address #348

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Can you get the tests pass?

**Comment by Manvi07** [comment]
> Can you get the tests pass?

@shreyasbapat tests pass on my system, after the second change.

**Comment by shreyasbapat** [comment]
Give it a rebase once?

**Comment by shreyasbapat** [comment]
YESSS! This is sympy issue! Rebase and the tests will pass!

**Comment by shreyasbapat** [comment]
These issues are fixed in https://github.com/einsteinpy/einsteinpy/commit/e0c7385f72ec22dda3a91c5a92b9333300ec964a

**Comment by Manvi07** [comment]
Done :smiley:

**Comment by shreyasbapat** [comment]
A little bad rebase :/

**Comment by shreyasbapat** [comment]
No changes here?

**Comment by ritzvik** [comment]
> No changes here?

Meaning ?

**Comment by ritzvik** [comment]
@shreyasbapat seems good enough!
BTW, that was quite a creative fix @Manvi07

**Comment by shreyasbapat** [comment]
Thanks @ritzvik for the kind words :p

https://github.com/einsteinpy/einsteinpy/issues/348#issuecomment-565123914

**Comment by shreyasbapat** [comment]
And this goes into the codebase :D

**Pull request merged**
