### PR TITLE
Move to 3.8

### LINKED ISSUE #358: Support Python 3.8
🐞 **Problem**

Form version 0.3.0, EinsteinPy should be tested on Python 3.8 also! 

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by ritzvik**
Fixes #358

### CODE REVIEW

**Comment by ritzvik** [comment]
Moving quality checks to GitHub actions because CircleCI only allows 4 parallel builds. So if we are going to add python 3.8, maybe we should offload some jobs from CircleCI.

**Comment by shreyasbapat** [comment]
Don't do it!

_______________________________________
This email is sent from a smartphone. Please ignore grammatical mistakes
and typographical errors.
_______________________________________

**Comment by shreyasbapat** [comment]
I've taken care of this on my local branch.

_______________________________________
This email is sent from a smartphone. Please ignore grammatical mistakes
and typographical errors.
_______________________________________

**Comment by ritzvik** [comment]
okay!

**Comment by ritzvik** [comment]
@shreyasbapat close or merge at your own will!

**Comment by ritzvik** [comment]
Well that’s a moot point. I don’t see any dependence between quality check and tests. And Mac OS and windows builds run irrespective of quality checks.

Anyway, do what you will.

Regards,
Ritwik

**Comment by shreyasbapat** [comment]
Yeah, the main issue is to keep everything on circleCI. Stay away from GitHub Actions :p

**Pull request closed without merging**
