### PR TITLE
Created a function for kerr-newman event horizon

### LINKED ISSUE #109: Coding the right event horizon for Kerr & Kerr-Newman space-time
🐞 **Problem**
As of now, in calculation of time-like trajectory in Kerr metric stops and raises a warning on reaching schwarzschild radius. But event horizon in kerr spacetime is smaller than schwarzschild radius. But the exact values need to be researched.

🎯 **Goal**
  - Research about the problem and specify the correct radius after which computation should stop in `metric/kerr.py`.

- [x] Kerr

- [ ] Kerr-Newman

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #109`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by shilpi1958**
Fixes #109 

@ritzvik  @shreyasbapat

### CODE REVIEW

**Comment by ritzvik** [comment]
Hi @shilpi1958 
Thanks for the PR
but your branch has become seriously messed up.

**Comment by shilpi1958** [comment]
yeah :( I am working on it

**Comment by shreyasbapat** [comment]
It's fine as long as you give me some output. We will work on the commits later on :)

**Comment by shreyasbapat** [comment]
Kindly work on getting the tests passed first :)

**Comment by shilpi1958** [comment]
Whenever I run kerrnewman_utils.py, I get the error

  File "kerrnewman_utils.py", line 42, in <module>
    Q, c=constant.c.value, G=constant.G.value, Cc=constant.coulombs_const.value
AttributeError: module 'einsteinpy.constant' has no attribute 'coulombs_const'

when I define coulombs_const'  in  kerrnewman_utils.py, it runs smoothly.

**Comment by ritzvik** [comment]
> Whenever I run kerrnewman_utils.py, I get the error
> 
> File "kerrnewman_utils.py", line 42, in 
> Q, c=constant.c.value, G=constant.G.value, Cc=constant.coulombs_const.value
> AttributeError: module 'einsteinpy.constant' has no attribute 'coulombs_const'
> 
> when I define coulombs_const' in kerrnewman_utils.py, it runs smoothly.

@shilpi1958 Didn't get what you are trying to say.
BTW good efforts from your side. Thanks

**Comment by shreyasbapat** [comment]
> when I define coulombs_const' in kerrnewman_utils.py, it runs smoothly.

Please define it from your side. And get the quality checks passed. We will see what to do next :)

**Comment by shreyasbapat** [comment]
Hi @shilpi1958 Are you still working on this?

**Comment by shilpi1958** [comment]
yes!

**Comment by shilpi1958** [comment]
@shreyasbapat 
made some changes!
How do I deal with the last test?

**Comment by ritzvik** [comment]
@shilpi1958 There are merge conflicts due to #203 . That's why appveyor CI is failing to run.

**Comment by shilpi1958** [comment]
oh, okay!

**Comment by shilpi1958** [comment]
Don't remember why I closed this!
@shreyasbapat

**Comment by shilpi1958** [comment]
Don't remember why I closed this!
@shreyasbapat

**Comment by shreyasbapat** [comment]
We will take care of this. Tomorrow!

**Comment by ritzvik** [comment]
@shilpi1958 , PR #472 is already underway and pretty much complete.

**Comment by shilpi1958** [comment]
Oh okay then! :)

**Pull request closed without merging**
