### PR TITLE
Fix doctrings, remove unnecessary "Inherits" statements

### LINKED ISSUE #465: Remove "inherited from blah-blah" in docstrings
🐞 **Problem**
With #442 , #412 was solved. This means explicitly mentioning where it is inherited from, is not required . For example,

https://github.com/einsteinpy/einsteinpy/blob/0e311bec1be2508a28ebd8a3f8b7b944db997269/src/einsteinpy/symbolic/tensor.py#L204-L208

🎯 **Goal**

Find instances of such docstrings and remove them. This is especially common in `Symbolic` module

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by yauneyz**
Fixes #465

@ritzvik

### CODE REVIEW

**Comment by ritzvik** [comment]
@yauneyz Thanks for the PR! Please squash the commits https://github.com/einsteinpy/einsteinpy/wiki/How-to-refactor-commits

Then it's good to go.

**Comment by yauneyz** [comment]
Looks like that rebase attempt didn't go so well. Let me try that again

**Comment by yauneyz** [comment]
Okay I fixed it - one commit, with all the right changes.

**Comment by ritzvik** [comment]
Thanks @yauneyz , I’m gonna merge!
With you, we hit 50 contributors. 🥂

**Pull request merged**
