### PR TITLE
Further speed up computing Christoffel symbol for Kerr metric.

### PR DESCRIPTION
**Pull request by raphaelreyna**
Fixes # 119

### CODE REVIEW

**Comment by ritzvik** [comment]
Hi @raphaelreyna,
I couldn't see any discrepancies in your approach, but still they are not passing the tests.
I don't know why. So I have implemented the desired changes on your line of thought, and made a few improvements myself, like not reassigning `chl[i][k][l] = chl[i][l][k] = val` when `k==l`. So I've made a little more rearrangements.
```
nonzero_christoffels_list = [
    (0, 0, 1),
    (0, 0, 2),
    (0, 1, 3),
    (0, 2, 3),
    (0, 1, 0),
    (0, 2, 0),
    (0, 3, 1),
    (0, 3, 2),
    (1, 0, 0),
    (1, 1, 1),
    (1, 2, 2),
    (1, 3, 3),
    (2, 0, 0),
    (2, 1, 1),
    (2, 2, 2),
    (2, 3, 3),
    (1, 0, 3),
    (1, 1, 2),
    (2, 0, 3),
    (2, 1, 2),
    (1, 2, 1),
    (1, 3, 0),
    (2, 2, 1),
    (2, 3, 0),
    (3, 0, 1),
    (3, 0, 2),
    (3, 1, 0),
    (3, 1, 3),
    (3, 2, 0),
    (3, 2, 3),
    (3, 3, 1),
    (3, 3, 2),
]  #: Precomputed list of tuples consisting of indices of christoffel symbols which are non-zero in Kerr Metric
```
```
def christoffels(c, r, theta, Rs, a):
    """
    Returns the 3rd rank Tensor containing Christoffel Symbols for Kerr Metric

    Parameters
    ----------
    c : float
        Speed of light
    r : float
        Distance from the centre
    theta : float
        Angle from z-axis
    Rs : float
        Schwarzschild Radius
    a : float
        Black Hole spin factor

    Returns
    -------
    ~numpy.array
        Numpy array of shape (4,4,4)

    """
    invg = metric_inv(c, r, theta, Rs, a)
    dmdx = dmetric_dx(c, r, theta, Rs, a)
    chl = np.zeros(shape=(4, 4, 4), dtype=float)
    for _, k, l in nonzero_christoffels_list[0:4]:
        val1 = dmdx[l][0][k] + dmdx[k][0][l] - dmdx[0][k][l]
        val2 = dmdx[l][3][k] + dmdx[k][3][l] - dmdx[3][k][l]
        chl[0][k][l] = chl[0][l][k] = 0.5 * (invg[0][0] * (val1) + invg[0][3] * (val2))
        chl[3][k][l] = chl[3][l][k] = 0.5 * (invg[3][0] * (val1) + invg[3][3] * (val2))
    for i, k, l in nonzero_christoffels_list[8:16]:
        chl[i][k][l] = 0.5 * (
            invg[i][i] * (dmdx[l][i][k] + dmdx[k][i][l] - dmdx[i][k][l])
        )
    for i, k, l in nonzero_christoffels_list[16:20]:
        chl[i][k][l] = chl[i][l][k] = 0.5 * (
            invg[i][i] * (dmdx[l][i][k] + dmdx[k][i][l] - dmdx[i][k][l])
        )
    return chl
```
I've taken the indices of type `(i, k, k)` and grouped them alongside each other for `i=1 & 2`, so that I do not need 2 assignments like `chl[i][k][l]=chl[i][l][k]=some value`.

If you agree with it, kindly implement the changes in a subsequent commit

Thanks again for your interest @raphaelreyna

**Comment by ritzvik** [comment]
@raphaelreyna 
Another little optimization:
In the first for loop, omit the `dmdx[0][k][l]` and `dmdx[3][k][l]`, beacuse they are always zero.
So,
```
val1 = dmdx[l][0][k] + dmdx[k][0][l]
val2 = dmdx[l][3][k] + dmdx[k][3][l]
```

**Comment by shreyasbapat** [comment]
Some tests are failing @raphaelreyna !

**Comment by shreyasbapat** [comment]
Also, some merge conflicts!

**Comment by ritzvik** [comment]
Hi @raphaelreyna ,
I don't think cutting down further loops is going to help in computations, as more computation is taking place inside the loops, the overall complexity remain approximately the same.

On the other hand, it increases the complexity for anyone reading the code. Suggestions?

BTW, thanks again @raphaelreyna

**Comment by ritzvik** [comment]
@raphaelreyna , your PR has a lot of redundant commits as well, and your master branch has become quite a mess. It would be difficult to fix and you may have to squash the commits.

So I was proposing I implement your changes with PR #117 , and make you the author of the commit.

Again, suggestions?

**Comment by raphaelreyna** [comment]
@ritzvik Sorry for the mess with the commits, I am still trying to figure out git. Also how can I test before pushing to avoid all of the redundancy.
Also, yeah I think you're right about it not really being worth it to to cut down on the for loops, I'll be changing that back.
I also see the point you make in #116, and while I do not know how to directly implement that style of indexing, I try to address the issue of needlessly creating and destroying arrays by caching them.

**Comment by raphaelreyna** [comment]
@ritzvik, and yeah I'm okay with your suggestion of implementing the changes with PR #117.

**Comment by ritzvik** [comment]
> @ritzvik Sorry for the mess with the commits, I am still trying to figure out git. Also how can I test before pushing to avoid all of the redundancy.
> Also, yeah I think you're right about it not really being worth it to to cut down on the for loops, I'll be changing that back.
> I also see the point you make in #116, and while I do not know how to directly implement that style of indexing, I try to address the issue of needlessly creating and destroying arrays by caching them.

Changing indexing style on all the code-base is a huge work, and that's not going to affect much. Another PR can take care of #116 .  
Should I take your changes and implement them in #117 , along with making you the author of the commit?
We may have to fix your master branch. Ping me on on riot personally, I'll walk you through it.

**Comment by ritzvik** [comment]
> @ritzvik, and yeah I'm okay with your suggestion of implementing the changes with PR #117.

okay

**Comment by ritzvik** [comment]
@raphaelreyna See this.

**Pull request closed without merging**
