### PR TITLE
add moon to bodies

### LINKED ISSUE #234: Add more Bodies to the bodies module
🐞 **Problem**

Currently, the bodies module only has 2 bodies. The list can be extended.

🎯 **Goal**

A better plotting experience

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by SuyashSalampuria**
Fixes #234 

@shilpi1958 @shreyasbapat  please review
I have added moon as a body 
Please review

### CODE REVIEW

**Comment by ritzvik** [comment]
You may be missing the line `Moon = _Moon()`, to make this coherent with other predefined bodies.

Thanks for opening the PR :)

**Comment by ritzvik** [comment]
https://docs.einsteinpy.org/en/latest/dev_guide.html#code-linting
The quality checks are not passing. Please see the above link for details.

Also, please try to squash the commits. Apart from these, everything seems fine :)

**Comment by SuyashSalampuria** [comment]
Done it @ritzvik 
Sorry for delay as there were problems due the corona outbreak

**Comment by ritzvik** [comment]
I understand your problem. Same with me 😐

LGTM

**Pull request merged**
