### PR TITLE
Geodesic issues

### LINKED ISSUE #410: Improve __str__ and __repr__ messages in Geodesic Module
🐞 **Problem**

The geodesic module has very less informative string representation. It should be starting with:

"Geodesic Object ... "

Think about a better message.

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in the comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by nimeshvashistha**
Fixes #410 

@shreyasbapat

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Alright @nimeshvashistha , you were finally able to resolve the merge conflicts! So, now we would find why your tests fail. Can you open the CI log and investigate? 

Ping me if you are unable to understand which logs to check.

**Comment by ritzvik** [comment]
This PR would have merge conflicts due to #435 .

**Comment by shreyasbapat** [comment]
Are you still working on this?

**Comment by nimeshvashistha** [comment]
No, but i made some changes which show in #435

**Comment by ritzvik** [comment]
> No, but i made some changes which show in #435

Okay, closing this then :)
Thanks!!

**Pull request closed without merging**
