### PR TITLE
fixed tests to be theoritically consistent

### PR DESCRIPTION
**Pull request by ritzvik**
Also, removed the tests which simulated particles moving greater than speed of light

### CODE REVIEW

**Comment by ritzvik** [comment]
CircleCI build failed. Problem on their side.

**Comment by ritzvik** [comment]
@shreyasbapat kindly merge this.

**Comment by shreyasbapat** [comment]
I took a week's break from open source. Sorry for every delay!

**Comment by shreyasbapat** [comment]
It introduced a build fail in CircleCI

**Pull request merged**
