### PR TITLE
Deleted vacuum_metrics module from symbolics(src) and tests(symbolic)

### LINKED ISSUE #468: Remove a deprecated module
🐞 **Problem**
Completely remove
https://github.com/einsteinpy/einsteinpy/blob/0e311bec1be2508a28ebd8a3f8b7b944db997269/src/einsteinpy/symbolic/vacuum_metrics.py#L7

Take care of removing tests and examples(if present anywhere)

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by Gagan-Shenoy**
Removed deprecated module vacuum_metrics  from symbolic and test_symbolic
Fixes #468

### CODE REVIEW

**Comment by ritzvik** [comment]
Thanks for the PR.
The tests aren’t passing.

**Comment by Gagan-Shenoy** [comment]
Did I delete an important file?

**Comment by ritzvik** [comment]
Maybe you need to remove the entry from `symbolic/__init__.py`

**Comment by Gagan-Shenoy** [comment]
Removed it from _init_.py but didnt work

**Comment by ritzvik** [comment]
You would need to remove the relevant files from `docs/source/api` folder and the relevant entries.
Also, search of examples where this module is used and fix them (if there's one)

**Comment by ritzvik** [comment]
@Gagan-Shenoy Thanks ! Everything looks great. I would like you to rebase the branch.
https://github.com/einsteinpy/einsteinpy/wiki/How-to-refactor-commits

Also, you may have your name and email set wrongly in your local git. https://help.github.com/en/github/using-git/setting-your-username-in-git

**Comment by Gagan-Shenoy** [comment]
Is it done?
I rebase the branch as you said

**Comment by shreyasbapat** [comment]
Fix the git config locally and redo the commits.

**Comment by ritzvik** [comment]
Superseded by #478 
Thanks for the efforts, @Gagan-Shenoy

**Pull request closed without merging**
