### PR TITLE
Add __str__ and __repr__ for Body Class #386

### LINKED ISSUE #386: Add __str__ and __repr__ for Body Class
🐞 **Problem**

Very much related to #380 but for Bodies module.
🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by mkhalid-s**
Fixes #386

### CODE REVIEW

**Comment by ritzvik** [comment]
I'm not the right guy to review 
cc @shreyasbapat 

BTW @mkhalid-s , cheers to your first PR 🎉

**Comment by ritzvik** [comment]
Try to pass the quality checks. Try running `tox -e reformat`

**Comment by mkhalid-s** [comment]
> Try to pass the quality checks. Try running `tox -e reformat`

@ritzvik  Thanks it worked.

> I'm not the right guy to review
> cc @shreyasbapat
> 
> BTW @mkhalid-s , cheers to your first PR 🎉

@ tx cheers :) yeah.. I just clicked on the first reviewer in the selection. Will tag @shreyasbapat  onwards.

**Comment by mkhalid-s** [comment]
@ritzvik @shreyasbapat  Do I have to write test coverage for Body class?

**Comment by shreyasbapat** [comment]
Also if we can resolve the issues highlighted by @pep8speaks , that would also be good

**Comment by mkhalid-s** [comment]
> Also if we can resolve the issues highlighted by @pep8speaks , that would also be good

@shreyasbapat  tox is reformatting and the operator pops down to the next line.

**Comment by mkhalid-s** [comment]
> I would appreciate if you can sqaush the commits for obvious reasons, rebase and I will merge it.

@shreyasbapat Done! 👍

**Comment by mkhalid-s** [comment]
> Also if we can resolve the issues highlighted by @pep8speaks , that would also be good

**Comment by shreyasbapat** [comment]
Congrats for your first contribution @mkhalid-s ! Hope to see you around more often :)

**Comment by ritzvik** [comment]
@mkhalid-s , please update your email in your local git account. Kindly use the same email you used to sign up with github, else your commits won't be associated with your github profile.

Maybe [this](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-in-git) can help.

**Comment by mkhalid-s** [comment]
> Congrats for your first contribution @mkhalid-s ! Hope to see you around more often :)


> @mkhalid-s , please update your email in your local git account. Kindly use the same email you used to sign up with github, else your commits won't be associated with your github profile.
> 
> Maybe [this](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-in-git) can help.

@shreyasbapat Thanks, man! Sure will gradually increase my contribution to this repo.
@ritzvik yaa, I have updated my local git now with my email id.

**Pull request merged**
