### PR TITLE
Changed warning category to PendingDeprecationWarning

### LINKED ISSUE #200: Change Warning Type in coordinate utils
🐞 **Problem**
When executing `from einsteinpy.utils import something` `UserWarning` is raised.

🎯 **Goal**
Change warning type to `PendingDeprecationWarning`

💡 **Possible solutions**

See :
  - https://docs.python.org/3/library/exceptions.html#PendingDeprecationWarning
  - https://docs.python.org/3/library/warnings.html#warnings.warn

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by abhijeetmanhas**
Fixes #200 

Changed warning category from `UserWarning` (which was default warning) to `PendingDeprecationWarning` in files given below:-

- `src/einsteinpy/utils/bl_coord_transforms.py`

- `src/einsteinpy/utils/coord_transforms.py `

### CODE REVIEW

**Comment by shreyasbapat** [comment]
You will first have to get the quality checks passed :)

**Comment by abhijeetmanhas** [comment]
I cannot understand  why my commits can't pass `CircleCI: quality` checks.
 In details, under `check Black style` division of quality test, it shows:

> would reformat /home/circleci/repo/src/einsteinpy/utils/coord_transforms.py
would reformat /home/circleci/repo/src/einsteinpy/utils/bl_coord_transforms.py
All done! 💥 💔 💥
2 files would be reformatted, 39 files would be left unchanged.
Exited with code 1

Can anyone help me out?

**Comment by abhijeetmanhas** [comment]
Thanks @shreyasbapat, all checks passed!
Is something else required in the code?

**Comment by shreyasbapat** [comment]
Please squash the commits into one as there are more than one merge commits in this PR.

**Pull request closed without merging**
