### PR TITLE
[WIP] JPLEphem module addition

### LINKED ISSUE #98: jit all the functions which are slow
🐞 **Problem**

Some methods are tooo slow! For which we brought `einsteinpy.ijit.jit`
🎯 **Goal**
Make einsteinpy fast!

💡 **Possible solutions**
Identify the slow methods, and

```
from einsteinpy.ijit import jit

@jit
def ..
```
Very easy.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by Tushar-Tyagi**
Addresses: #41

To do : Add tests.

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Astropy is already a dependency. You were not supposed to take the complete module. Plus they follow BSD 3 Claused Copyright. We can't do this

**Comment by Tushar-Tyagi** [comment]
@shreyasbapat can you please check again?

**Comment by shreyasbapat** [comment]
@Tushar-Tyagi The module can be changed a little bit added as a class method to Geodesics Class! If you still want to work on it, DM me on matrix, I will tell you what has to be done.

**Comment by Tushar-Tyagi** [comment]
@shreyasbapat I will start working on it after a week or so.

**Pull request closed without merging**
