### PR TITLE
Weyl jupyter notebook

### LINKED ISSUE #312: Notebook example for Weyl, Einstein and Ricci
🎯 **Goal**
 * Create jupyter notebook example for Weyl

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by OVSofia**
Fixes #312

### CODE REVIEW

**Comment by shreyasbapat** [comment]
This would need a Rebase :) 
And can you squash the commits please?

**Comment by shreyasbapat** [comment]
Also the notebook should be added to `index.ipynb` . Because that is the first place user visits!

**Comment by OVSofia** [comment]
I'm going to redimension the imagens in a next commit, and if everything looks good I will  squash the commits

**Comment by ritzvik** [comment]
> I'm going to redimension the imagens in a next commit, and if everything looks good I will squash the commits.
> (and the rebase)

@OVSofia , great work !! I've replaced screenshots of Ricci Tensor and Weyl Tensor in `index.ipynb` with real-life pictures of Ricci and Weyl (with captions ofc). Otherwise, the gallery became very monotonous!
Did some slight edits.
Now,
  - pull the changes
  - rebase the branch
  - squash the commits

Then it's ready!

**Comment by ritzvik** [comment]
Let's concentrate on #308 after this, I've been procrastinating :(

**Comment by ritzvik** [comment]
DONE!
cc @shreyasbapat

**Pull request merged**
