### PR TITLE
Fixed the Logo of the readme

### LINKED ISSUE #604: Clean up the logo for the readme
🐞 **The rough edges and bad color scheme for dark mode**

🎯 **Fix the logol**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by D3FaltXD**
Fixes #604 

The logo is now visible in dark mode of github

@rohan-paul

### CODE REVIEW

**Comment by JeS24** [comment]
Hey @D3FaltXD, thanks for opening this PR. While your edit to the logo does make it look better in dark mode, the light-mode preview looks jagged:
image

Any way to fix this? Also, could you sync the recent changes to the main branch to your fork, so that the tests pass?

**Comment by D3FaltXD** [comment]
Sure will clean up the edges... but white color of Einstein won't be visible in light mode.
Do you want to me change the color for that?

**Comment by JeS24** [comment]
> Sure will clean up the edges... but white color of Einstein won't be visible in light mode. Do you want to me change the color for that?

I think, we do need a color change, but that's for later. For now, let's just have a smooth white ~2px border around `Einstein`, so that it remains nearly identical to the current logo in light mode, while also being legible in dark mode.

**Comment by JeS24** [comment]
Fixed via [705b35](https://github.com/einsteinpy/einsteinpy/commit/705b351dd80e4f1e81a4a66f0957178695e55c6b).

**Pull request closed without merging**
