### PR TITLE
Ship tests outside package

### LINKED ISSUE #466: Stop shipping tests
🐞 **Problem**

From `0.3.0` we can stop shipping tests in the package itself. 

🎯 **Goal**

Put tests outside.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by anish29292**
Move tests outside

Fixes #466

@shreyasbapat

### CODE REVIEW

**Comment by anish29292** [comment]
@shreyasbapat

**Comment by anish29292** [comment]
@ritzvik

**Comment by shreyasbapat** [comment]
@anish29292 You need to have some patience in order to contribute. I will review this today.

**Comment by shreyasbapat** [comment]
First I will ask you to configure your local git client and redo the commit. `git reset` will be useful in doing this.

**Comment by shreyasbapat** [comment]
Is this being worked upon?

**Comment by ritzvik** [comment]
The PR seems inactive. Closing this one.

**Pull request closed without merging**
