### PR TITLE
Vectorized functions

### LINKED ISSUE #52: Using numpy.vectorize instead of for loops for a better code
https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/utils/coord_transforms.py#L199-L204
For loop can be replaced by np.vectorize by vectorizing the functions used in the for loop

### PR DESCRIPTION
**Pull request by pmk21**
Fixes #52 

@ritzvik Vectorized the necessary functions. Probably needs little more testing.

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Hi @pmk21 ,
Thanks a lot for your Pull Request! As you see, the Quality tests are failing! In that case, you might want to run `black` on these two files as in the CI Logs:

```
would reformat /home/circleci/repo/src/einsteinpy/utils/coord_transforms.py
would reformat /home/circleci/repo/src/einsteinpy/utils/bl_coord_transforms.py
All done! 💥 💔 💥
2 files would be reformatted, 28 files would be left unchanged.
Exited with code 1
```
Just use `black coord_transforms.py` and `black  bl_coord_transforms.py` after `cd`ing into `utils`.

Once quality checks pass, I would do a thorough review.

**Comment by shreyasbapat** [comment]
The CI will not fix as the numba guys do not have the wheels for python 3.5!

**Comment by ritzvik** [comment]
@shreyasbapat I wrote two separate tests to check it and it worked well with the new tests as well as old ones. The changes are good to go.
Thanks for the contribution @pmk21 .
As as with the new tests, I think they should go the same PR. Should I make a PR on @pmk21 's fork?

**Comment by ritzvik** [comment]
@shreyasbapat sooner or later we have to do something about the CI thing.

**Comment by ritzvik** [comment]
@pmk21 add the following test snippets to the end of files.

in `tests/test_utils/test_bl_coords_transforms.py` add these lines at the end
```


@pytest.mark.parametrize(
    "vec, a",
    [
        (
            np.array(
                [
                    [21.0, 300, 0.33, 4.0, 1.0, -10.0, -1, -2],
                    [1.0, 3, 0.1, 5.0, 1.0, 100.0, -11, 2],
                    [1.0, 3, 0.1, 0, 1.0, 0, -11, 2],
                ]
            ),
            0.4,
        )
    ],
)
def test_BL2C_8dim(vec, a):
    list1 = list()
    for v in vec:
        nv = np.hstack(
            (
                v[0],
                utils.BLToCartesian_pos(v[1:4], a),
                v[4],
                utils.BLToCartesian_vel(v[1:4], v[5:8], a),
            )
        )
        list1.append(nv)
    arr1 = np.array(list1)
    arr2 = utils.BL2C_8dim(vec, a)
    assert_allclose(arr1, arr2, rtol=0.0, atol=1e-5)

```


in `tests/test_utils/test_coords_transforms.py` add these lines at the end
```


@pytest.mark.parametrize(
    "vec",
    [
        (
            np.array(
                [
                    [21.0, 300, 0.33, 4.0, 1.0, -10.0, -1, -2],
                    [1.0, 3, 0.1, 5.0, 1.0, 100.0, -11, 2],
                    [1.0, 3, 0.1, 0, 1.0, 0, -11, 2],
                ]
            )
        )
    ],
)
def test_S2C_8dim(vec):
    list1 = list()
    for v in vec:
        nv = np.hstack(
            (
                v[0],
                utils.SphericalToCartesian_pos(v[1:4]),
                v[4],
                utils.SphericalToCartesian_vel(v[1:4], v[5:8]),
            )
        )
        list1.append(nv)
    arr1 = np.array(list1)
    arr2 = utils.S2C_8dim(vec)
    assert_allclose(arr1, arr2, rtol=0.0, atol=1e-5)

```

and kindly remember to apply `black` to both files.
Thanks again

**Comment by pmk21** [comment]
Yes, I will work on it soon @ritzvik .

**Comment by pmk21** [comment]
No problems, love contributing. How can I be of help or contribute more?

**Comment by shreyasbapat** [comment]
> How can I be of help or contribute more?

You can help us solve any of the issues ! 

Thanks a lot!

**Pull request merged**
