### PR TITLE
fix relative imports to absolute

### LINKED ISSUE #377: Fix-up imports within coordinates module
🐞 **Problem**
[PEP8](https://www.python.org/dev/peps/pep-0008/#id23) recommends absolute imports and most of einsteinpy abides by it, exception being the `coordinates` module.

🎯 **Goal**

  - Identify the relative imports and fix them up.

💡 **Possible solutions**

  - To get an inkling about what I am saying, see any other module within einsteinpy, (`symbolic` or `metric`)

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by rohitsanj**
changed relative imports to absolute across entire codebase

Fixes #377 

@shreyasbapat @ritzvik

### CODE REVIEW

**Comment by ritzvik** [comment]
Please don’t change the `__init__.py`s. They are meant to be like that.

**Comment by rohitsanj** [comment]
Alright, I thought so but I changed it since it was absolute in a few places already, like `src/einsteinpy/plotting/senile/__init__.py`

Do you want me to change those absolute imports to relative as well?

**Comment by ritzvik** [comment]
> > Please don’t change the `__init__.py`s. They are meant to be like that.
> 
> Alright, I thought so but I changed it since it was absolute in a few places already, like [`src/einsteinpy/plotting/senile/__init__.py`](https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/plotting/senile/__init__.py), [`src/einsteinpy/plotting/__init__.py`](https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/plotting/__init__.py)
> 
> https://github.com/einsteinpy/einsteinpy/blob/f73abb3e04afdcf70567d9d49d856bb585369057/src/einsteinpy/plotting/__init__.py#L1-L4
> 
> Do you want me to change these absolute imports to relative as well?

@shreyasbapat ? I’ll wait for his review

**Comment by ritzvik** [comment]
Meanwhile can you edit `einsteinpy.coordinates` to `einsteinpy.coordinates.conversion` in these 2 places ?

https://github.com/einsteinpy/einsteinpy/blob/bf3737c1f2ddfe9b89362aaf7b7d045bd7a05ea9/src/einsteinpy/coordinates/core.py#L4-L8

https://github.com/einsteinpy/einsteinpy/blob/bf3737c1f2ddfe9b89362aaf7b7d045bd7a05ea9/src/einsteinpy/coordinates/velocity.py#L4-L8

BTW, kudos to your first PR 🎉  . Hope to see you around!

**Comment by shreyasbapat** [comment]
Alright. Leave `senile`. Its supposed to go away soon anyways.

**Comment by shreyasbapat** [comment]
I will review before merging. Give me some time.

**Comment by ritzvik** [comment]
Don't touch any `__init__`s. Sorry for the troubles @rohitsanj

**Comment by rohitsanj** [comment]
@ritzvik no problem! :) 

Let me know if my changes are alright now

**Comment by ritzvik** [comment]
@rohitsanj A grand welcome to the community 💯 . Thanks for your contribution.

Merging.

**Pull request merged**
