### PR TITLE
Update shadow.py

### PR DESCRIPTION
**Pull request by Relativist1**
Fixes #432 >

### CODE REVIEW

**Comment by Relativist1** [comment]
Can't believe it...
finally!

**Comment by ritzvik** [comment]
@Relativist1 are you sure of this?
Because you seem to be moving from an adaptive method to a fixed step-size one.
Any particular reasons to do this?

**Comment by ritzvik** [comment]
What I see is the `tol` tolerance parameter is too low in `quadrature` function by default. Maybe we can increase the tolerance, and get a corresponding increase in step-size, reducing the time taken.

**Comment by shreyasbapat** [comment]
We need to move to a fixed step size method.

**Comment by shreyasbapat** [comment]
This was toooooo slow

**Comment by ritzvik** [comment]
Ok then, merge it :)

Regards,
Ritwik

**Comment by Relativist1** [comment]
Actually no matter how much I increased the tolerance it wouldn't matter matter.
Fixed size was getting the samw results in no time. 
So thats why.!
Also it gives no warnings as it used to be and sometimes kernel died too!

**Comment by ritzvik** [comment]
> Actually no matter how much I increased the tolerance it wouldn't matter matter.
> Fixed size was getting the samw results in no time.
> So thats why.!
> Also it gives no warnings as it used to be and sometimes kernel died too!

This sure is fast! I saw that

**Comment by ritzvik** [comment]
Thanks Saurabh!

**Pull request merged**
