### PR TITLE
[WIP] Release 0.2.1 cherry-picks

### PR DESCRIPTION
**Pull request by ritzvik**
Fixes #<Put_Issue_Number_Here>

### CODE REVIEW

**Comment by ritzvik** [comment]
@shreyasbapat Let's gear up for `0.2.1` . 
I was not sure whether to include commits of #318 , I don't think changing package dependencies should happen between patch releases.

Anyways, waiting for #316 , #286

**Comment by shreyasbapat** [comment]
We can make this release after the SOCIS period is over.

**Comment by shreyasbapat** [comment]
This PR needs to hold as of now! But I will make sure that all the Symbolic related cherry picks are included. One of my PR will supersede it once #327 is merged!

**Comment by shreyasbapat** [comment]
And. DON'T DELETE YOUR BRANCH!

**Pull request closed without merging**
