### PR TITLE
Kerr time-like geodesics

### PR DESCRIPTION
**Pull request by ritzvik**
Attempt to address #38

### CODE REVIEW

**Comment by ritzvik** [comment]
@shreyasbapat Update What's new and front page in ReadTheDocs in accordance with the PR after merging it. I can't figure it out what to write instead of ```einsteinpy 0.1.0 - 2019-03-08```

**Comment by shreyasbapat** [comment]
Why is coverage reducing?

**Comment by ritzvik** [comment]
> Why is coverage reducing?

@shreyasbapat it is actually increasing I think!

**Comment by shreyasbapat** [comment]
I am talking about this part! https://codecov.io/gh/einsteinpy/einsteinpy/pull/101/diff?src=pr&el=tree#D10-195
Can you test this as well?

**Comment by shreyasbapat** [comment]
> Update What's new and front page in ReadTheDocs in accordance with the PR after merging it. I can't figure it out what to write instead of einsteinpy 0.1.0 - 2019-03-08

I didn't get what you mean by this?

**Comment by ritzvik** [comment]
> > Update What's new and front page in ReadTheDocs in accordance with the PR after merging it. I can't figure it out what to write instead of einsteinpy 0.1.0 - 2019-03-08
> 
> I didn't get what you mean by this?

Never mind!

**Comment by ritzvik** [comment]
@shreyasbapat added the tests as required. Codecov not triggering for some reason. I think the overall coverage should exceed 90% now

**Comment by shreyasbapat** [comment]
Codecov was triggered

**Comment by shreyasbapat** [comment]
But the Results are somewhat not shown!

**Comment by shreyasbapat** [comment]
Can you do:

`git commit --amend`

and then

`git push -f origin kerrtry`

**Comment by shreyasbapat** [comment]
Good! Now good to merge!

**Pull request merged**
