### PR TITLE
Update portions of symbolic module

### LINKED ISSUE #360: Add Kerr and Kerr-Newman metric in Boyer-Lindquist coordinates to predefined metrics
🐞 **Problem**
`symbolic/predefined/vacuum_solutions.py` needs Kerr and Kerr-Newman Metrics. Implement them similar to already implemented `Schwarzschild()` in the same file.

💡 **Possible solutions**

  - [x] Kerr (c737c8b)
  - [ ] Kerr Newman

The metrics can be found be simple search on wikipedia. Also implementation can be found in `utils/kerr_utils.py` and `utils/kerrnewman_utils.py`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by ritzvik**
Partially Fix #360 

Would be waiting for #387

### CODE REVIEW

**Comment by shreyasbapat** [comment]
The wait ends :p

**Comment by shreyasbapat** [comment]
BTW, why in the world are you solving a good first issue?

**Comment by ritzvik** [comment]
> BTW, why in the world are you solving a good first issue?

I don't think, implementing this was a good first issue. Still, I am leaving half of that open!


There are many changes other than that!

**Comment by shreyasbapat** [comment]
Ok

**Pull request merged**
