### PR TITLE
Added more parameters

### LINKED ISSUE #41: Visualise orbits from JPLHorizons and JPLEphem
This will be a nice feature to add as most users won't be bothering about finding the actual velocity and distance metrics. Hope we can get that from here?

### PR DESCRIPTION
**Pull request by NithyaNN3**
Fixes #41 

@shreyasbapat

### CODE REVIEW

**Comment by ritzvik** [comment]
This PR has 0 changes, according to GitHub.

**Comment by ritzvik** [comment]
For quality checks, https://docs.einsteinpy.org/en/latest/dev_guide.html#code-linting

**Comment by JeS24** [comment]
We decided not to do #41. Perhaps, this PR can be closed? @NithyaNN3 @shreyasbapat

**Comment by JeS24** [comment]
Closing this PR. cref: https://github.com/einsteinpy/einsteinpy/issues/41#issuecomment-648981610

**Pull request closed without merging**
