### PR TITLE
Deleted vacuum_metrics module from docs and src

### LINKED ISSUE #468: Remove a deprecated module
🐞 **Problem**
Completely remove
https://github.com/einsteinpy/einsteinpy/blob/0e311bec1be2508a28ebd8a3f8b7b944db997269/src/einsteinpy/symbolic/vacuum_metrics.py#L7

Take care of removing tests and examples(if present anywhere)

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request.
 * Add this in the comments:
 	- `Addresses #<put issue number here>` if you are partially fixing the issue.
 	- `Fixes #<put issue number here>` if you are completely fixing the issue.
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by Gagan-Shenoy**
Deleted vacuum_metrics module from docs/source/symbolic/ , src/einsteinpy/symbolic and src/einstienpy/tests .
Fixes #468

### CODE REVIEW

**Comment by Gagan-Shenoy** [comment]
I redid the commits and changed user.name.

**Comment by ritzvik** [comment]
As long as you don’t set up you user.email same as what you used to set up GitHub, your commits wouldn’t link to your profile. That’s what Shreyas was trying to say.

**Comment by Gagan-Shenoy** [comment]
Ok so I'll have to change the mail and do the commits again ryt.

**Comment by ritzvik** [comment]
Yes. That’s pretty much it.

Regards,
Ritwik

**Comment by ritzvik** [comment]
Superseded by #478

**Pull request closed without merging**
