### PR TITLE
Addresses #108

### PR DESCRIPTION
**Pull request by raphaelreyna**
Addresses #108

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Hi @raphaelreyna  ,
Thanks a lot for your Pull Request! As you see, the Quality tests are failing! In that case, you might want to run `black` on this file as in the [CI Logs](https://circleci.com/gh/einsteinpy/einsteinpy/1141?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) :

```
would reformat /home/circleci/repo/src/einsteinpy/utils/kerr_utils.py
All done! 💥 💔 💥
1 file would be reformatted, 29 files would be left unchanged.
Exited with code 1
```
Just run `black kerr_utils.py`  after `cd`ing into `utils`.

Once quality checks pass, I would do a thorough review.

**Comment by raphaelreyna** [comment]
Hi @shreyasbapat,
I have run `kerr_utils.py` through `black` as per your suggestion.
It seems as though there in now a dependency error, but I can't figure out what to do about it.
Any suggestions?
I apologize for needing these things explained to me, I am pretty new at contributing on github and working with continuous integration.

**Comment by ritzvik** [comment]
Hi @raphaelreyna ,
First of all, lot of thanks for contributing.
It's very weird for python 3.5 build to fail when 3.6 & 3.7 are passing. It may be issue from the CI provider side. It happens sometimes.
Secondly, it's very sleek what you did in the code. Kudos for that.
Could you change in ordering in `nonzero_christoffels_list` within the first 8 indices at the top of file so that we can do
```
for _, k, l in nonzero_christoffels_list[0:4]:
    chl[0][k][l] = chl[0][l][k] = some value
    chl[3][k][l] = chl[3][l][k] = some value
```
or something like that to save computation. It matters a lot when it called 100000 times when calculating geodesics.
Kindly remember to apply `black` after your changes 😃

**Comment by shreyasbapat** [comment]
Oh! this is happening everywhere!

**Comment by shreyasbapat** [comment]
https://status.circleci.com/
https://status.appveyor.com/

**Comment by shreyasbapat** [comment]
@raphaelreyna Can you do this?

`git commit --amend`

and then 

`git push -f origin master`

to trigger the CI builds

**Comment by raphaelreyna** [comment]
Hi @ritzvik,
Thank you for your kind words. I will look into implementing your suggested changes later today and tomorrow!

**Comment by raphaelreyna** [comment]
So I have implemented the suggestion given by @ritzvik, and it looks like all of the quality checks have been passed. I feel like it's ready for a review, is this where I would ask for that?

**Comment by ritzvik** [comment]
> So I have implemented the suggestion given by @ritzvik, and it looks like all of the quality checks have been passed. I feel like it's ready for a review, is this where I would ask for that?

@raphaelreyna Thanks a lot for taking the pain to look into the project and implementing the suggested changes. It's great that the tests have passed and it is surely ready for merging. Also, the the problem on the Numba's  side seems to be resolved. That's why the tests are working again.

@raphaelreyna I have been on github for the past 1.5 moths and you can consider me pretty novice in open source development. But still, I had my fair share of learning. So one advice from my side is always make branches in your fork while working on any bug/feature. Never directly make changes to master. Secondly, try to make the commit messages a little more concise and informative.

If you are interested in working further, or are just interested, kindly join the Riot Chat [here](https://riot.im/app/#/room/#einsteinpy:matrix.org)

Finally, I would ask @shreyasbapat to merge this.

Thanks again @raphaelreyna

**Comment by ritzvik** [comment]
@shreyasbapat Also close #108 on merging

**Comment by shreyasbapat** [comment]
Thanks a lot!

**Pull request merged**
