### PR TITLE
Addresses Issue #541 Refine Jupyter Notebooks Page

### PR DESCRIPTION
**Pull request by rachittshah**
### Problem

https://docs.einsteinpy.org/en/latest/jupyter.html
The Juypter Notebook page needed descriptions for the heading and descriptions.

### Goal
Increase readability and make user-friendly.
### Possible solutions
Add links to articles/refer books/youtube videos

@shreyasbapat 
@kakirastern 

Please let me know about the improvements/changes.

### CODE REVIEW

**Comment by kakirastern** [comment]
Thanks for the PR @godslayer201!

**Comment by JeS24** [comment]
@godslayer201 [This](https://github.com/matplotlib/matplotlib/issues/4067#issuecomment-753666340) will help with the test errors.

**Comment by godslayer201** [comment]
> @godslayer201 [This](https://github.com/matplotlib/matplotlib/issues/4067#issuecomment-753666340) will help with the test errors.

Thank you @JeS24 for the help! I was wondering why I was getting test errors. 

Will work on this and send an updated PR by the end of the week😁

**Comment by JeS24** [comment]
#620 fixes #541.

**Pull request closed without merging**
