### PR TITLE
Changed the default config parameter to 'u' for the __init__ function.

### PR DESCRIPTION
**Pull request by DylanBrdt**
Addresses #361 

@ritzvik

### CODE REVIEW

**Comment by ritzvik** [comment]
@DylanBrdt , thanks for opening your first PR. 
Can you do one more thing? Please do the corresponding change in the docstring [here](https://github.com/einsteinpy/einsteinpy/blob/6c4378e3c64c5b0e02934a0b84b6cf7183ed1e06/src/einsteinpy/symbolic/vector.py#L22)

**Comment by DylanBrdt** [comment]
Yeah sorry for my inexperience, just trying to learn how to contribute to Open-Source Programs. Let me know if you need anything else regarding this issue.

**Comment by ritzvik** [comment]
@DylanBrdt , No problem. Everybody starts something new somewhere down the line. One suggestion from my side is that, please open new branches everytime for development.

Merging this :)

**Comment by shreyasbapat** [comment]
Congrats on your first contribution @DylanBrdt :)

**Pull request merged**
