### PR TITLE
Addresses #626

### PR DESCRIPTION
**Pull request by jjmcinto**
Addresses #626 

Added colours and chart titles to demonstrate new functionality in example notebooks.

### CODE REVIEW

**Comment by JeS24** [comment]
Thank you for the PR. I have approved the test workflows. Will review sometime today.

**Comment by JeS24** [comment]
@jjmcinto Some additional changes would be needed. I have listed them below:
1. Can you fix the issue with the labels on the last plot's Y-axis in the "Visualizing Precession..." notebook (`XYZ vs Lambda`)?
2. And in the "Using Geodesics..." notebook,
   1. Remove unused imports.
   2. Add 1 cell showing the use of `aspect_ratio` in the `plot()` method. Right now, only "auto" is used.
3. In either case, remove the last (empty) cell, after running the notebooks.

Other than these, I think, we are good to go. Although, are you using Jupyter Lab / Notebook to make the edits or VS Code? Because with VS Code, interactive plot states won't be saved, which would break the documentation preview. Even in Jupyter Lab, the states won't be saved till "Settings -> Save Widget State Automatically" is enabled.

**Comment by jjmcinto** [comment]
> @jjmcinto Some additional changes would be needed. I have listed them below:
> 
>     1. Can you fix the issue with the labels on the last plot's Y-axis in the "Visualizing Precession..." notebook (`XYZ vs Lambda`)?
> 
>     2. And in the "Using Geodesics..." notebook,
>        
>        1. Remove unused imports.
>        2. Add 1 cell showing the use of `aspect_ratio` in the `plot()` method. Right now, only "auto" is used.
> 
>     3. In either case, remove the last (empty) cell, after running the notebooks.
> 
> 
> Other than these, I think, we are good to go. Although, are you using Jupyter Lab / Notebook to make the edits or VS Code? Because with VS Code, interactive plot states won't be saved, which would break the documentation preview. Even in Jupyter Lab, the states won't be saved till "Settings -> Save Widget State Automatically" is enabled.

I am editing the notebooks exclusively in Jupyter.

Here are the states of the remaining issues (and I have yet to push today's changes to my fork):

Issue 3: Removing the empty cells is a good idea. I'll do that.

Issue 1: I am not sure how what you are picturing for a solution regarding the Y-axis of that plot. X1 and X2 are on very different scales; putting them on the same scale would either flatten one or put the other off of the chart. Can you clarify what it is that you want to see?

Issue 2:
	Unused imports removed!
	Problem: There appears to be a bug in the `StaticGeodesicPlotter`, where it calls `set_aspect`. It looks like mplot3d only supports “auto” aspect_ratio; setting aspect_ratio to any other value in the allowed list (i.e. "equal", "equalxy", "equalyz", "equalxz") causes the following error (WLOG showing “equal” in this example): 

`NotImplementedError: Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'.`

I could tackle the underlying problem and try to make the aspect_ratio feature work but that would be outside of the scope of the documentation issue.

So, for now, are we good with just using ‘auto’ in the documentation, or have I missed something?

For full context, here is the stack trace:
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
/var/folders/2q/xxwjly4j6qj8nsvhbpvhxjn80000gn/T/ipykernel_3405/2267309747.py in <module>
      1 sgpl = StaticGeodesicPlotter()
----> 2 sgpl.plot(geod, color="green", title="3D Geodesic Plot", aspect="equal")
      3 #sgpl.plot(geod, color="green", title="3D Geodesic Plot")
      4 sgpl.show()

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/einsteinpy-0.5.dev0-py3.9.egg/einsteinpy/plotting/geodesic/static.py in plot(self, geodesic, figsize, color, title, aspect)
    204 
    205         self.ax.plot(x, y, z, "--", color=color, label=geodesic.kind + " Geodesic")
--> 206         self.ax.set_aspect(aspect)
    207 
    208         if title:

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpl_toolkits/mplot3d/axes3d.py in set_aspect(self, aspect, adjustable, anchor, share)
    321         """
    322         if aspect != 'auto':
--> 323             raise NotImplementedError(
    324                 "Axes3D currently only supports the aspect argument "
    325                 f"'auto'. You passed in {aspect!r}."

NotImplementedError: Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'.

**Comment by JeS24** [comment]
@jjmcinto Regarding issue 1, this is what I am referring to:
New docs
The issue is with the seemingly overlapping ticks & labels on the X & Y-axes for the 3 coordinates. Apparently, the culprit is [L300 in static.py](https://github.com/einsteinpy/einsteinpy/blob/a998861e5714a7a3887a1013f0a9977d7fd7b15e/src/einsteinpy/plotting/geodesic/static.py#L300), which shouldn't be there. Removing it fixes the issue:
image

This is technically outside the scope of a mere documentation update, but if you are interested, you can create a new issue regarding it (use these screenshots if you want or link to this reply), make this small change, which would also fix the display in the notebook, and tag that issue # here.

**Comment by JeS24** [comment]
@jjmcinto Regarding issue 3, more options for `aspect` were added in `matplotlib>=3.7.0` (See [this](https://matplotlib.org/3.8.0/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.set_aspect.html#mpl_toolkits.mplot3d.axes3d.Axes3D.set_aspect)). If you upgrade your `matplotlib`, it should allow that code to run without issues.

As a sidenote, we were also tracking a related issue around naming convention parity between the `matplotlib` and `plotly` (or, `StaticGeodesicPlotter` and `InteractiveGeodesicPlotter` respectively) backends in #624. If you are interested, you can contribute there too, though it's not needed for this PR.

**Review by JeS24 — CHANGES_REQUESTED** [review]
I have reviewed the code. Minor changes requested.

**Comment by jjmcinto** [comment]
> @jjmcinto Regarding issue 3, more options for `aspect` were added in `matplotlib>=3.7.0` (See [this](https://matplotlib.org/3.8.0/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.set_aspect.html#mpl_toolkits.mplot3d.axes3d.Axes3D.set_aspect)). If you upgrade your `matplotlib`, it should allow that code to run without issues.
> 
> As a sidenote, we were also tracking a related issue around naming convention parity between the `matplotlib` and `plotly` (or, `StaticGeodesicPlotter` and `InteractiveGeodesicPlotter` respectively) backends in #624. If you are interested, you can contribute there too, though it's not needed for this PR.

Okay, I pushed an update to my branch, addressing issues 2 and 3. I would like to leave issue 1 to someone else for now, as it is out of scope.

**Comment by jjmcinto** [comment]
@JeS24  I believe this branch is ready to pull. Can we make that happen?

**Comment by jjmcinto** [comment]
@JeS24 I am new the fast-forwarding with Git. I attempted to pull the latest changes from the main branch and the result suggested that I have the latest changes. Can you give me a hint about fast-forwarding my branch?

Here are the commands I sent and their results:
`$ git fetch https://github.com/einsteinpy/einsteinpy.git
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Total 7 (delta 5), reused 7 (delta 5), pack-reused 0
Unpacking objects: 100% (7/7), 523 bytes | 34.00 KiB/s, done.
From https://github.com/einsteinpy/einsteinpy
 * branch            HEAD       -> FETCH_HEAD

$ git merge
Already up to date.`

Running `sgpl.plot(geod, color="green", title="3D Geodesic Plot", aspect="equal")` gave an error, suggesting that plot is not working on my machine:
`Expected one of ['auto', 'data', 'manual', 'cube']. Received 'equal'.`

Here is the full error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/2q/xxwjly4j6qj8nsvhbpvhxjn80000gn/T/ipykernel_21701/1500321816.py in <module>
      1 gpl.clear() # In Interactive mode, `clear()` must be called before drawing another plot, to avoid overlap
----> 2 gpl.plot(geod, color="green", title="Geodesic Plot", aspect="equal")
      3 gpl.show()

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/einsteinpy-0.5.dev0-py3.9.egg/einsteinpy/plotting/geodesic/interactive.py in plot(self, geodesic, color, title, aspect, aspect_ratio)
    175 
    176         if aspect not in aspects:
--> 177             raise ValueError(
    178                 f"Invalid aspect type. Expected one of {aspects}. Received '{aspect}'."
    179             )

ValueError: Invalid aspect type. Expected one of ['auto', 'data', 'manual', 'cube']. Received 'equal'.

**Comment by JeS24** [comment]
@jjmcinto This should help you update your fork - https://github.com/einsteinpy/einsteinpy/wiki/Development-tips#after-your-pr-is-merged. Note that, you may have to commit or undo or stash any change prior to updating. I recommend you first update the fork and then make any new changes and commit.

And, the error is because you are using `gpl` or `GeodesicPlotter`, which defaults to `InteractiveGeodesicPlotter` (`plotly` backend), instead of `StaticGeodesicPlotter` (`matplotlib` backend). The `aspect` parameter in `StaticGeodesicPlotter` takes `equal`. It seems, you are making that change in the `Using Geodesics...` notebook, but I was referring to the `Visualizing Precession...` notebook in my last comment, under the "Plotting the geodesic" subsection. As long as you are using `matplotlib>=3.7.0`, it should work.

As a sidenote, this argument naming disparity is the crux of #624.

**Comment by jjmcinto** [comment]
@JeS24 I ran the [fast-forward](https://github.com/einsteinpy/einsteinpy/wiki/Development-tips#after-your-pr-is-merged), confirmed that line 300 in static.py had changed on my local copy and pushed the remaining changes to my branch. However, the overlapping labels remain. I re-ran the 'fast-forward' process repeatedly, restarted the kernel and restarted my computer, and yet the overlapping labels persist.

Can you think of anything else I might try to get your update to work on my machine?

**Comment by JeS24** [comment]
@jjmcinto As far as I can tell, your `main` branch is still behind by 1 commit (this one - https://github.com/jjmcinto/einsteinpy/compare/main...einsteinpy:einsteinpy:main):
image 

As a result, [L300 still exists](https://github.com/jjmcinto/einsteinpy/blob/d8e7755b0ba7847810ca3e42403e797fe4537839/src/einsteinpy/plotting/geodesic/static.py#L300) in your fork, which is the culprit behind the overlapping labels on the plot.

Did you push to origin after merging your local `main` branch with upstream's (einsteinpy/einsteinpy's) `main` branch, like so:
```bash
git merge upstream/main
git push origin main
```
The last git command should push the local `main` branch changes to origin, i.e., jjmcinto/einsteinpy/main. To verify, you can check https://github.com/jjmcinto/einsteinpy/blob/main/src/einsteinpy/plotting/geodesic/static.py#L300 after running that command. If you still see the `self.ax = plt.axes()` line there, then the fork isn't updated on origin, even if your local repo is up to date.

**Comment by jjmcinto** [comment]
Okay, I did that final step (merge and push) and confirmed that the offending line is gone on my local and remote repositories, but the overlap persists. I am running the notebook on my local machine; my local copy of static.py is up to date (verified manually). It looks like it should be working. I will take another look tomorrow.

**Comment by JeS24** [comment]
@jjmcinto On my end, using your `main` branch, the plot comes out fine:
image
I think, we can proceed with the merge.

**Comment by JeS24** [comment]
@jjmcinto In case, this problem shows up in the ReadTheDocs build, I'll revert and reopen this.

**Comment by jjmcinto** [comment]
Hey cool! Let me know if you need any further action on my part, eh?

**Comment by JeS24** [comment]
@jjmcinto RTD PDF builds are broken at the moment. So, cannot check if the overlapping labels issue will show up there. However, I doubt it will. Thank you for the contribution.

**Pull request merged**
