### PR TITLE
Fix #401

### LINKED ISSUE #401: Consider replacing np.moveaxis with sympy permutedims
🐞 **Problem**
Currently, to permute dimensions in a tensor, we first convert it to numpy object, apply `np.moveaxis` and then revert back to sympy `Array`.

The instances are :

https://github.com/einsteinpy/einsteinpy/blob/dfc3bc281e296adbaa486e1f5e5f24fc02adeac3/src/einsteinpy/symbolic/tensor.py#L55-L61

https://github.com/einsteinpy/einsteinpy/blob/dfc3bc281e296adbaa486e1f5e5f24fc02adeac3/src/einsteinpy/symbolic/tensor.py#L363-L369

💡 **Possible solutions**

As of sympy > `1.4`, a new function [`permutedims`](https://docs.sympy.org/1.5.1/modules/tensor/array.html#sympy.tensor.array.permutedims) has been added.

Use this function to save the intermediate conversion into numpy object.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by atulmangat**
Fixes #401 

@ritzvik Please Review

### CODE REVIEW

**Comment by atulmangat** [comment]
image
Testing Logs for test_symbolic moudule

**Comment by ritzvik** [comment]
OK, lemme see

**Comment by ritzvik** [comment]
The implementation is not working as evident from the failing test and even if you rerun the `Playing with Contravariant and Covariant Indices in Tensors(Symbolic).ipynb` notebook in `docs/source/examples`, you can see that the outputs are significantly different.

Probably, it is not so straightforward, and maybe, you would have to figure it out.

Anyway, thanks for initiating this :)

**Comment by atulmangat** [comment]
please review @ritzvik @shilpi1958  @shreyasbapat

**Comment by shreyasbapat** [comment]
This looks good to me. Can you rebase and squash?

**Comment by atulmangat** [comment]
@ritzvik @shreyasbapat  please review

**Comment by shreyasbapat** [comment]
Your rebase did not happen correctly, moreover can you please limit the commits to 1 or 2?

**Comment by shreyasbapat** [comment]
Also, the diff shows #438 and a merge commit, which is why I said the rebase was not good.

**Comment by ritzvik** [comment]
@atulmangat thanks for this much needed PR.

There were a few bad commits and rebases, so this time I took the liberty of fixing them up myself, but you gotta take care of them next time onwards. I would really appreciate if you could explain what does sympy `permutedims` take as argument in a comment below.

I'm gonna merge. Cheers !!

**Comment by atulmangat** [comment]
@ritzvik @shreyasbapat sorry for that mess. I'm newbie in opensource I think I screwed up somewhere in rebase. I will take care of that in future.

**Comment by atulmangat** [comment]
**sympy.permutedims(t , perm)**  
Takes in 2 arguments -
t : sympy N-dim Array
perm : desired permutation of the indices.

Example : 
*t = numpy.zeros((2,3,4,5))*
*t = sympy.Array(t)*
*sympy.permutedims(t,[3,2,1,0]).shape*
will result in :
(5, 4, 3, 2)

**Pull request merged**
