### PR TITLE
Documentation feature

### LINKED ISSUE #267: Docs not present for Ricci Tensor & Vacuum Metrics
**Possible solutions**
  - Additions in `docs/source/api/symbolic/symbolic_index.rst`
  - New files `docs/source/api/symbolic/ricci.rst`, `docs/source/api/symbolic/vacuum_metric.rst`

  - Add `vacuum_metric` to `symbolic/__init__.py`

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by OVSofia**
Fixes #267

### CODE REVIEW

**Comment by ritzvik** [comment]
This needs a rebase
```
git pull --rebase upstream master
git push origin documentationFeature -f
```

`-f` for force push, as there is change in history.
This time I'm writing out the specific commands, next time onwards you would know what to do when I say rebase :)

**Comment by ritzvik** [comment]
After this ready for merging

**Comment by ritzvik** [comment]
@OVSofia 
Also, from kindly learn what is squashing commits.
https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

Not this time, but I might ask you to squash commits sometime in future.

Thanks

**Comment by shreyasbapat** [comment]
I will ask you to do one more rebase :) 

I will merge some PR's before this one :/ 
Sorry for the trouble!

**Comment by shreyasbapat** [comment]
LGTM

**Pull request merged**
