### PR TITLE
#236 Update the User Guide

### LINKED ISSUE #236: Update the User Guide to the newest version
🐞 **Problem**

https://docs.einsteinpy.org/en/latest/user_guide.html

This does not use the `CartesianDifferential` objects that we created a while ago.

Refer to : https://docs.einsteinpy.org/en/latest/examples/Visualizing_advance_of_perihelion_of_a_test_particle_in_Schwarzschild_space-time.html

for understanding the changes done.
🎯 **Goal**

To get the User Guide up and running! 

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by shilpi1958**
Fixes #236

@shreyasbapat 
@ritzvik

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Your local git configurations are not correct. :)

**Comment by shilpi1958** [comment]
Corrected them :)

> Your local git configurations are not correct. :)

Corrected them!

**Comment by ritzvik** [comment]
Hi @shilpi1958 ,
Thanks for this. Wouldn't it be great if you can update the `Coordinate Conversion` section also.
This one https://github.com/einsteinpy/einsteinpy/blob/1e51e2179450a5cb1e22b93629fd7bd67e945d96/docs/source/user_guide.rst#coordinate-conversion

**Comment by shreyasbapat** [comment]
Yes, you will have to separate out `coordinates` and `symbolic` from utils :D

**Comment by ritzvik** [comment]
> Yes, you will have to separate out `coordinates` and `symbolic` from utils :D

`symbolic` we would see later because specific classes for `Kerr` and all are not implemented till now.

**Comment by shilpi1958** [comment]
On it :D !

**Comment by ritzvik** [comment]
@shilpi1958 , one more small thing to do, remove the first point from `future plans`.
https://github.com/einsteinpy/einsteinpy/blob/1e51e2179450a5cb1e22b93629fd7bd67e945d96/docs/source/user_guide.rst#future-plans

**Pull request merged**
