### PR TITLE
Fix: Deprecation warnings by astropy.units

### LINKED ISSUE #221: handle DeprecationWarning in tests
🐞 **Problem**
In all CI tests, `astropy.units` is raising `DeprecationWarning`.  
```
=============================== warnings summary ===============================
venv/lib/python3.6/site-packages/einsteinpy/utils/bl_coord_transforms.py:8
  /home/circleci/repo/venv/lib/python3.6/site-packages/einsteinpy/utils/bl_coord_transforms.py:8: PendingDeprecationWarning: This module will be deprecated in EinsteinPy v0.3.0. Please switch to `einsteinpy.coordinates`.
    PendingDeprecationWarning,

venv/lib/python3.6/site-packages/einsteinpy/utils/coord_transforms.py:8
  /home/circleci/repo/venv/lib/python3.6/site-packages/einsteinpy/utils/coord_transforms.py:8: PendingDeprecationWarning: This module will be deprecated in EinsteinPy v0.3.0. Please switch to `einsteinpy.coordinates`.
    PendingDeprecationWarning,

src/einsteinpy/tests/test_plotting/test_staticgeodesicplotter.py::test_plot_calls_draw_attractor_Manualscale
  /home/circleci/repo/venv/lib/python3.6/site-packages/astropy/units/quantity.py:855: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
    return super().__ne__(other)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================== 99 passed, 3 warnings in 60.34 seconds ====================
```

🎯 **Goal**
  - Fix it.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #221`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by shakeabi**
Fixes #221 

@shreyasbapat @ritzvik What dya think?

### CODE REVIEW

**Comment by shakeabi** [comment]
@ritzvik @shreyasbapat  Went through the error raised by CodeFactor. It makes sense. "is" is used for identity testing and it's unreliable to use in these cases.

**Comment by ritzvik** [comment]
@shakeabi I would be reviewing in a while and suggest some changes.
Thanks @shakeabi

**Comment by ritzvik** [comment]
@shakeabi The codefactor thing is right I guess. Not every thing is suitable to be used with `is` or `is not`.
One more workaround, try `cl.get_curr_plot_radius.value != -1`

**Comment by shreyasbapat** [comment]
What I suggest is use some tolerance and assert if the value is as close as possible to -1

**Comment by ritzvik** [comment]
> What I suggest is use some tolerance and assert if the value is as close as possible to -1

Nopes, -1 is a token value here, and technically it should have been 0.
See https://github.com/einsteinpy/einsteinpy/blob/master/src/einsteinpy/plotting/geodesics_static.py#L47

The test is just to check whether, `get_curr_plot_radius` is getting updated or not(MY GUESS). Maybe we can ping whoever wrote these lines for better clarity.

**Comment by rishi-s8** [comment]
@ritzvik @shreyasbapat @shakeabi What I can see here is probably this piece of code was written to bypass Codecov. The default value of ```get_curr_plot_radius``` is 0, but it is being set equal to the radius in the code. 
** Possible Fix **
Assuming ```get_curr_plot_radius``` can *never* equal to 0:
- In ```test_plot_calls_draw_attractor_Manualscale```, ```cl.get_curr_plot_radius``` is with unit ```u.m```. Hence, change conflict to ```assert cl.get_curr_plot_radius != 0 * u.m```.
- In ```test_plot_calls_draw_attractor_AutoScale```, ```cl.get_curr_plot_radius``` is without units. Hence, change conflict to ```assert cl.get_curr_plot_radius != 0```.

Why one is with units and the other without units is something I don't have an answer for yet. 😓 

P.S. This will fix the DeprecationWarning and the Codefactor issue. :) Tried and tested.

**Comment by ritzvik** [comment]
@rishi-s8 The discrepancy you pointed out shouldn't have passed code review! This issue seems a lot bigger than fixing `DeprecationWarning`. Thanks for pointing out!

**Comment by shreyasbapat** [comment]
I will fix this on my own

**Comment by ritzvik** [comment]
> I will fix this on my own

Still on it ?

**Comment by ritzvik** [comment]
This is no longer a problem 🎉 
Closing!

**Pull request closed without merging**
