### PR TITLE
Follows PEP8 

### PR DESCRIPTION
**Pull request by r0cketr1kky**
Fixes #418 

@ritzvik

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Not sure what you are trying to achieve through this Pull Request, but it is actually doing the opposite of what it is claiming :p

**Comment by r0cketr1kky** [comment]
Yeah, I’m running into a lot of errors, even though locally it says that I
have cleared them.

**Comment by shreyasbapat** [comment]
Not sure if you really understood. So, we do follow highest code quality standards in the market. And everything is automated. So you can't possibly introduce something new to it. :)
And try to solve the existing issues, rather than creating one to solve it.

**Comment by r0cketr1kky** [comment]
Understood and noted.
Thanks a lot for helping me because I’m very new to this.

**Comment by ritzvik** [comment]
> Understood and noted. Thanks a lot for helping me because I’m very new to this.

@r0cketr1kky I'm closing this PR then. We hope that you continue to contribute in the library in meaningful ways :)

**Pull request closed without merging**
