### PR TITLE
Draft Pull Request for implementation of Null Geodesics & Radiative Transfer

### PR DESCRIPTION
**Pull request by JeS24**
Draft in progress. More commits incoming.

Fixes: #105, #106 
Potentially fixes/addresses: #103, #113, #122, #141 

@shreyasbapat

### CODE REVIEW

**Comment by JeS24** [comment]
CI checks will probably not pass, at the moment.

**Comment by shreyasbapat** [comment]
Adaptive Mesh Refinement?

**Comment by shreyasbapat** [comment]
Makes sense. I will start with adding KS Coordinates

**Comment by JeS24** [comment]
> Adaptive Mesh Refinement?

This is potentially an advancement in that (AMR) direction. The proposed integrator uses adaptive meshing near problematic areas of the spacetime (coordinate singularities). This should be extensible to #103.

**Comment by JeS24** [comment]
> Makes sense. I will start with adding KS Coordinates

`coordinates` should not see major changes. Am committing the likely changes now.

**Pull request closed without merging**
