### PR TITLE
Geodesic

### LINKED ISSUE #410: Improve __str__ and __repr__ messages in Geodesic Module
🐞 **Problem**

The geodesic module has very less informative string representation. It should be starting with:

"Geodesic Object ... "

Think about a better message.

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in the comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by nimeshvashistha**
Fixes #410 

@shreyasbapat

### CODE REVIEW

**Comment by shreyasbapat** [comment]
I will review in some time.

**Comment by shreyasbapat** [comment]
You need to open the CI logs, check which tests are failing and fix them!

**Comment by shreyasbapat** [comment]
Also, there is some conflict. Kindly fix it

**Comment by shreyasbapat** [comment]
@nimeshvashistha Are you still on it?

**Comment by nimeshvashistha** [comment]
Yes

**Pull request closed without merging**
