### PR TITLE
Updated: test_coord_transform and test_velocity_transform with unittests

### PR DESCRIPTION
**Pull request by sidmttl**
Addresses #423

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Your quality checks are failing :)

Have a look at the contribution guidelines, we have a section on code linting there.

**Comment by ritzvik** [comment]
@sidmttl Are you still on it ?

For your code-linting reference see [this](https://docs.einsteinpy.org/en/latest/dev_guide.html#code-linting)

**Comment by ritzvik** [comment]
you would also require to rebase the branch.

**Comment by sidmttl** [comment]
Thank you for being patient with me, I apologize for the delay, I had an emergency.

yes i am on it, the isort issue is there i will fix it asap.

**Comment by ritzvik** [comment]
> Thank you for being patient with me, I apologize for the delay, I had an emergency.
> 

No problem! Open source is about patience and community bonding. Every developer is valuable to us.

**Comment by ritzvik** [comment]
One more thing, as the `upstream` has moved forward while you were working on it. Can you rebase and squash.
To rebase:
```
git remote add upstream https://github.com/einsteinpy/einsteinpy.git
git pull --rebase upstream master
```
And then squash the commits into one, and force push

**Comment by ritzvik** [comment]
@shreyasbapat should be add a small section about rebasing and organizing commits in docs?
We are expecting a substantial number of contributors in coming days.

**Comment by sidmttl** [comment]
Thank you for helping,

By mistake i have used my master branch in fixing the issue, instead of creating a new branch, can you suggest any remedy.

**Comment by ritzvik** [comment]
Complete this PR on master only. From next time, take care :)

Regards,
Ritwik

**Comment by ritzvik** [comment]
Also, squashing the eight commits into one would be of great help

https://github.com/wprig/wprig/wiki/How-to-squash-commits

Regards,
Ritwik

**Comment by sidmttl** [comment]
Thank you for the help.

**Comment by ritzvik** [comment]
LGTM, merging.
Congrats on your first PR @sidmttl

**Comment by ritzvik** [comment]
@sidmttl 
See https://github.com/einsteinpy/einsteinpy-0.3.0-paper/issues/10 and please do the needful.

**Pull request merged**
