### PR TITLE
Create Getting_started.rst

### PR DESCRIPTION
**Pull request by spino17**
Documentation related to getting started with the library.

### CODE REVIEW

**Comment by shreyasbapat** [comment]
https://circleci.com/gh/einsteinpy/einsteinpy/463?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

See this!

**Comment by shreyasbapat** [comment]
This will need a rebase onto the current master!
screenshot from 2019-02-25 16-15-16

**Comment by shreyasbapat** [comment]
@spino17 Updates?

**Comment by ritzvik** [comment]
#71 taking care of the pull request.
@shreyasbapat  close this

**Pull request closed without merging**
