### PR TITLE
Add KerrPlotter class.

### PR DESCRIPTION
**Pull request by Varunvaruns9**
Add KerrPlotter class to plot event horizon and ergosphere of
Kerr Black Holes with some tests.

Fixes: #123.

@shreyasbapat FYI

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Hi @Varunvaruns9 :) Thanks for chiming here on this issue :) 
I have some considerations regarding the code. 

But I will address them once your quality check pass :)

**Comment by Varunvaruns9** [comment]
@shreyasbapat Fixed the quality tests, although the three tests still give a ValueError.

Sorry for the mess, was having a hard time as I am inexperienced with these python tests.

**Comment by shreyasbapat** [comment]
> Sorry for the mess, was having a hard time as I am inexperienced with these python tests.

No problem, everyone creates a mess in tests when do it for the first time. :)

**Comment by shreyasbapat** [comment]
@Varunvaruns9 Do you need any help in this?

**Comment by Varunvaruns9** [comment]
Yes, with the tests. The error says expected two values but got zero, when the functions '_calc_.....' clearly return a tuple.

**Comment by Varunvaruns9** [comment]
@shreyasbapat Fixed the tests and rebased. 

> I have some considerations regarding the code.

What else is to be done?

**Comment by shreyasbapat** [comment]
Thanks @Varunvaruns9 :) 
Will review today

**Comment by ritzvik** [comment]
@Varunvaruns9 The PR is not showing merge conflicts but still, see to it as API breaking changes have been introduced in the `metric` module.

**Comment by Varunvaruns9** [comment]
@ritzvik Thanks for the comment. I will check and update the PR if any changes are needed.

**Comment by shreyasbapat** [comment]
Update needed

**Comment by Varunvaruns9** [comment]
Sorry for the delay, was busy this week.

**Comment by ritzvik** [comment]
Now that geodesics plotter is in place, maybe this can be closed??

**Comment by ritzvik** [comment]
Closing! 
Hate to see so many lines going down the drain.

**Pull request closed without merging**
