### PR TITLE
Add tests for plotting as well

### PR DESCRIPTION
**Pull request by shreyasbapat**

### CODE REVIEW

**Comment by ritzvik** [comment]
Kr li codacy integrate? 
🤣 
@shreyasbapat

**Comment by ritzvik** [comment]
codacy hata de!
@shreyasbapat

**Comment by ritzvik** [comment]
@shreyasbapat Ye PR thik krke merge kr de!

**Comment by ritzvik** [comment]
> @shreyasbapat Ye PR thik krke merge kr de!

@shreyasbapat codecov bad jeyega!

**Comment by shreyasbapat** [comment]
Closed for #63

**Pull request closed without merging**
