### PR TITLE
Raising & Lowering indices

### LINKED ISSUE #256: Implement index raising and lowering in Tensors
🐞 **Problem**
We have no way to know whether the Tensor has contravariant or covariant indices

🎯 **Goal**

The indices must be properly formatted in front of a symbol.

  - [x] Metric Tensor
  - [x] Christoffel Symbols
  - [x] Riemann Tensor
  - [x] Ricci Tensor
  - [x] Weyl Tensor

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by ritzvik**
Addresses #256

### CODE REVIEW

**Comment by ritzvik** [comment]
@shreyasbapat Coverage increased!

**Comment by ritzvik** [comment]
DON'T MERGE NOW

**Comment by shreyasbapat** [comment]
Okay!

**Comment by shreyasbapat** [comment]
It's not in the release!

**Pull request merged**
