### PR TITLE
Urgent fix in hypersurface docs

### PR DESCRIPTION
**Pull request by ritzvik**
@shreyasbapat

### CODE REVIEW

**Comment by shreyasbapat** [comment]
I didn't mean this!

**Comment by shreyasbapat** [comment]
Ok. Let this PR be right here! I will take care of it!

**Comment by ritzvik** [comment]
! MERGE

**Comment by shreyasbapat** [comment]
> ! MERGE

Patience. Don't put Urgent Label until necessary!

**Comment by shreyasbapat** [comment]
Closed in https://github.com/einsteinpy/einsteinpy/commit/b8d12b0ca4f03f2fe393ec11cdfe1b2a9cd22e98

**Pull request closed without merging**
