### PR TITLE
Add interactive 3d plotter

### PR DESCRIPTION
**Pull request by Varunvaruns9**
@shreyasbapat 

newplot

### CODE REVIEW

**Comment by Varunvaruns9** [comment]
codeclimate 😞

**Comment by shreyasbapat** [comment]
Can we include scaling here also? 
And then some last basic steps such as putting appropriate units to the axes, labels and stuff.

**Comment by Varunvaruns9** [comment]
There are a few problems in drawing the attractor in 3d. Since the scales of the axes are different, the sphere becomes a 3d ellipse. We can use a 3d ellipse with dimensions such that it looks like a sphere when drawn but neither Matplotlib nor Plotly has any inbuilt method to do that. We can draw it manually with a mesh but it would be costly to draw a smooth figure.

> And then some last basic steps such as putting appropriate units to the axes, labels and stuff.
Also, what else needs to be added? @shreyasbapat

**Comment by shreyasbapat** [comment]
Right. Can you give me an example where it looks like that!

**Comment by shreyasbapat** [comment]
Also, for some reasons not understandable to be there are merge conflicts

**Comment by Varunvaruns9** [comment]
Figure_1
@shreyasbapat This is what we'll get if we try to draw a sphere.

**Comment by shreyasbapat** [comment]
Can we make any progress with this?

**Comment by JeS24** [comment]
#612 fixes the scaling / aspect issue.

**Pull request closed without merging**
