### PR TITLE
Added more badges in docs

### LINKED ISSUE #78: Badges in Documentation and README don't match
🐞 **Problem**
screenshot from 2019-03-02 01-25-30
screenshot from 2019-03-02 01-25-35

🎯 **Goal**
These two set of badges should match!

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by hrishi32**
Fixes #78 
@shreyasbapat

### CODE REVIEW

**Comment by ritzvik** [comment]
@hrishi32 rebase your branch with einsteinpy master

**Comment by shreyasbapat** [comment]
As pointed out by @ritzvik 
screenshot from 2019-03-02 14-20-05
It needs a rebase onto the current master.

**Comment by shreyasbapat** [comment]
A suggestion: Make a new branch for every pull request.

**Comment by hrishi32** [comment]
> @hrishi32 rebase your branch with einsteinpy master

Done. Thank you for pointing it out.

**Comment by shreyasbapat** [comment]
Cool. Thanks for the contribution!

**Pull request merged**
