### PR TITLE
improved navigation bar in docs

### LINKED ISSUE #218: Change Navigation Bar style in docs
🐞 **Problem**
The highlighted link is split in two lines, and there is no way to differentiate.

See for yourself at http://docs.einsteinpy.org/en/latest/

🎯 **Goal**
  - Make the index bulleted.

💡 **Possible solutions**
  - Tinker in `docs/source/_static/custom.css`
  - Hint : 
    ```
    div.sphinxsidebar ul {.....}
    ```

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #218`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by fiterace**
Fixes  #218 

@ritzvik

### CODE REVIEW

**Comment by ritzvik** [comment]
Hi @fiterace ,
What I was expecting is that one would override `div.sphinxsidebar ul` in `custom.css` and change `list-style` to `square`.
Anyways, your solution works, but it would be better if you can implement the above suggestion.

Thanks @fiterace

**Comment by fiterace** [comment]
@ritzvik I have added another commit. Is this correct?

**Comment by ritzvik** [comment]
@fiterace The PR looks good. That's what I wanted. Now it looks like this 😍 


I believe we can safely ignore the codefactor.
@fiterace Thanks very much for your first contribution.
@shreyasbapat Kindly Merge.

**Comment by ritzvik** [comment]
@fiterace The PR was alright. Why did you do a merge commit. Could you revert it.

**Comment by shreyasbapat** [comment]
Anyways! Merging the PR!

**Pull request merged**
