### PR TITLE
[WIP] Refactor of metric, utils module

### LINKED ISSUE #113: Refactor some functions in Schwarzschild and Kerr class
🐞 **Problem**
`calculate_trajectory()` and `calculate_trajectory_iterator()` in both `metric/schwarzschild.py` and `metric/kerr.py` have become a mess. Refactoring is required.

🎯 **Goal**
  - Refactor them such that both `cyclometic` and `cognitive` complexity remains low.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #113`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

### PR DESCRIPTION
**Pull request by JeS24**
Fixes #113, #141 
Also fixes some calculation errors at certain places

#### Current changes:
1. `metric` and `utils` merged
2. New `Metric` class added
3. Refactored `metric.Schwarzschild`, `metric.Kerr` and `metric.KerrNewman`

#### Pending changes:
- [x] Make specific metric classes in `metric` derive from `metric.Metric`
- [x] Move `time_velocity` out of `metric` and into `coordinates`.
    - [ ] Refactor `time_velocity` to make it solve for timelike component of 4-Velocity in any given metric.
    - [ ] Make `coordinate` calculate and return 4-Position and 4-Velocity, instead of 3-Pos and 3-Vel (as it is now).
- [ ] Move `calculate_trajectory` and  `calculate_trajectory_iterator` out of `metric` and into `integrator`
    - [ ] Refactors needed for these 2 functions
- [ ] Add warnings at relevant places.
- [ ] Remove `# - ????? Version/Warning` after review.

@shreyasbapat  Please review the current changes.

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Unless it takes up some shape, I can't review it

**Comment by JeS24** [comment]
@shreyasbapat I have postfixed `_new` to the _new_ predefined metric classes. They are too different from the old classes to merge directly. Need name suggestions.

**Comment by JeS24** [comment]
Checking code format issues now.

**Comment by shreyasbapat** [comment]
I don't see any new changes @JeS24 ? I think you are moving too sllowly.

**Comment by shreyasbapat** [comment]
Not sure what these 38 commits are supposed to mean?

**Comment by JeS24** [comment]
@shreyasbapat Rebase failures. This is not going anywhere. I am closing this PR. Let me copy over relevant changes to a separate branch.

**Pull request closed without merging**
