### PR TITLE
symbolic kerr

### PR DESCRIPTION
**Pull request by ritzvik**

### CODE REVIEW

**Comment by shreyasbapat** [comment]
Wait for me to merge #63

**Comment by shreyasbapat** [comment]
Please open the issue of isort and quote the issue from where you found this

**Comment by shreyasbapat** [comment]
You can rebase and happily remove the `isort` hack!

**Comment by ritzvik** [comment]
> Please open the issue of isort and quote the issue from where you found this

isort 4.3.5 is not running on my pc. It is alright till 4.3.4

**Comment by ritzvik** [comment]
> You can rebase and happily remove the `isort` hack!

Done btw

**Comment by shreyasbapat** [comment]
Please rebase and remove the versioning hack

**Comment by ritzvik** [comment]
BTW, happy to see 85% codecov

**Comment by ritzvik** [comment]
all done!

**Comment by shreyasbapat** [comment]
Merging!

**Comment by shreyasbapat** [comment]
Can we refer some issue here?

**Pull request merged**
