### PR TITLE
Added ephemerides using astroquery.jplhorizons

### PR DESCRIPTION
**Pull request by Manvi07**
Addresses #41 

Implemented using JPLHorizons from Astroquery.

### CODE REVIEW

**Comment by Manvi07** [comment]
@shreyasbapat How does the coverage get affected on adding a separate new file? :thinking:

**Comment by Manvi07** [comment]
@shreyasbapat How does the coverage get affected on adding a separate new file? :thinking:

**Comment by shreyasbapat** [comment]
Because coverage = total_tested_code / total_code * 100

**Comment by shreyasbapat** [comment]
Moreover, now that you know what has to be done :)
I will review this PR and give some code suggestions.

**Comment by shreyasbapat** [comment]
@Manvi07 I am waiting for #192 . Once that gets a green light we can move forward with this :)

**Comment by ritzvik** [comment]
@shreyasbapat Let's close stale PRs.
Anyway, GR is not required to solve dynamics of solar system objects. Newtonian mechanics does good enough job!

**Comment by shreyasbapat** [comment]
No, we are gonna do this!

**Comment by ritzvik** [comment]
That’s fine. But I was just asking that is there any need to do so. People would be just better off to calculate dynamics of conventional bodies in conventional softwares. Whatever accuracy EPY would give theoretically can’t be made possible practically because we are bound to use a finite `step_size`.

Regards,
Ritwik

**Pull request closed without merging**
